// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Protocolbuffers.h"

@class ChunkChecksumList;
@class ChunkChecksumList_Builder;
@class ChunkError;
@class ChunkErrorIndex;
@class ChunkErrorIndex_Builder;
@class ChunkError_Builder;
@class ChunkInfo;
@class ChunkInfo_Builder;
@class ChunkReference;
@class ChunkReference_Builder;
@class ErrorResponse;
@class ErrorResponse_Builder;
@class FileChecksumAuthorization;
@class FileChecksumAuthorizationList;
@class FileChecksumAuthorizationList_Builder;
@class FileChecksumAuthorization_Builder;
@class FileChecksumChunkReferences;
@class FileChecksumChunkReferences_Builder;
@class FileChecksumStorageHostChunkLists;
@class FileChecksumStorageHostChunkLists_Builder;
@class FileChunkError;
@class FileChunkError_Builder;
@class FileChunkList;
@class FileChunkList_Builder;
@class FileChunkLists;
@class FileChunkLists_Builder;
@class FileError;
@class FileError_Builder;
@class FileGroups;
@class FileGroups_Builder;
@class HostInfo;
@class HostInfo_Builder;
@class MethodCompletionInfo;
@class MethodCompletionInfoList;
@class MethodCompletionInfoList_Builder;
@class MethodCompletionInfo_Builder;
@class NameValuePair;
@class NameValuePair_Builder;
@class StorageContainerChunkList;
@class StorageContainerChunkList_Builder;
@class StorageContainerChunkLists;
@class StorageContainerChunkLists_Builder;
@class StorageContainerError;
@class StorageContainerErrorList;
@class StorageContainerErrorList_Builder;
@class StorageContainerError_Builder;
@class StorageHostChunkList;
@class StorageHostChunkList_Builder;
@class StorageHostChunkLists;
@class StorageHostChunkLists_Builder;

@interface ChunkServerRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ChunkInfo : PBGeneratedMessage {
@private
  BOOL hasChunkChecksum_:1;
  BOOL hasChunkEncryptionKey_:1;
  BOOL hasChunkLength_:1;
  BOOL hasChunkOffset_:1;
  NSData* chunkChecksum;
  NSData* chunkEncryptionKey;
  int32_t chunkLength;
  int32_t chunkOffset;
}
- (BOOL) hasChunkChecksum;
- (BOOL) hasChunkEncryptionKey;
- (BOOL) hasChunkLength;
- (BOOL) hasChunkOffset;
@property (readonly, retain) NSData* chunkChecksum;
@property (readonly, retain) NSData* chunkEncryptionKey;
@property (readonly) int32_t chunkLength;
@property (readonly) int32_t chunkOffset;

+ (ChunkInfo*) defaultInstance;
- (ChunkInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChunkInfo_Builder*) builder;
+ (ChunkInfo_Builder*) builder;
+ (ChunkInfo_Builder*) builderWithPrototype:(ChunkInfo*) prototype;

+ (ChunkInfo*) parseFromData:(NSData*) data;
+ (ChunkInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ChunkInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ChunkInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChunkInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChunkInfo_Builder : PBGeneratedMessage_Builder {
@private
  ChunkInfo* result;
}

- (ChunkInfo*) defaultInstance;

- (ChunkInfo_Builder*) clear;
- (ChunkInfo_Builder*) clone;

- (ChunkInfo*) build;
- (ChunkInfo*) buildPartial;

- (ChunkInfo_Builder*) mergeFrom:(ChunkInfo*) other;
- (ChunkInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChunkInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChunkChecksum;
- (NSData*) chunkChecksum;
- (ChunkInfo_Builder*) setChunkChecksum:(NSData*) value;
- (ChunkInfo_Builder*) clearChunkChecksum;

- (BOOL) hasChunkEncryptionKey;
- (NSData*) chunkEncryptionKey;
- (ChunkInfo_Builder*) setChunkEncryptionKey:(NSData*) value;
- (ChunkInfo_Builder*) clearChunkEncryptionKey;

- (BOOL) hasChunkLength;
- (int32_t) chunkLength;
- (ChunkInfo_Builder*) setChunkLength:(int32_t) value;
- (ChunkInfo_Builder*) clearChunkLength;

- (BOOL) hasChunkOffset;
- (int32_t) chunkOffset;
- (ChunkInfo_Builder*) setChunkOffset:(int32_t) value;
- (ChunkInfo_Builder*) clearChunkOffset;
@end

@interface NameValuePair : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasValue_:1;
  NSString* name;
  NSString* value;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* value;

+ (NameValuePair*) defaultInstance;
- (NameValuePair*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NameValuePair_Builder*) builder;
+ (NameValuePair_Builder*) builder;
+ (NameValuePair_Builder*) builderWithPrototype:(NameValuePair*) prototype;

+ (NameValuePair*) parseFromData:(NSData*) data;
+ (NameValuePair*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NameValuePair*) parseFromInputStream:(NSInputStream*) input;
+ (NameValuePair*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (NameValuePair*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NameValuePair*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (NameValuePair*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NameValuePair_Builder : PBGeneratedMessage_Builder {
@private
  NameValuePair* result;
}

- (NameValuePair*) defaultInstance;

- (NameValuePair_Builder*) clear;
- (NameValuePair_Builder*) clone;

- (NameValuePair*) build;
- (NameValuePair*) buildPartial;

- (NameValuePair_Builder*) mergeFrom:(NameValuePair*) other;
- (NameValuePair_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NameValuePair_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (NameValuePair_Builder*) setName:(NSString*) value;
- (NameValuePair_Builder*) clearName;

- (BOOL) hasValue;
- (NSString*) value;
- (NameValuePair_Builder*) setValue:(NSString*) value;
- (NameValuePair_Builder*) clearValue;
@end

@interface HostInfo : PBGeneratedMessage {
@private
  BOOL hasExpiry_:1;
  BOOL hasHostname_:1;
  BOOL hasMethod_:1;
  BOOL hasUri_:1;
  BOOL hasTransportProtocol_:1;
  BOOL hasTransportProtocolVersion_:1;
  BOOL hasScheme_:1;
  BOOL hasDatacenter_:1;
  BOOL hasPort_:1;
  int64_t expiry;
  NSString* hostname;
  NSString* method;
  NSString* uri;
  NSString* transportProtocol;
  NSString* transportProtocolVersion;
  NSString* scheme;
  NSString* datacenter;
  int32_t port;
  NSMutableArray* mutableHeadersList;
}
- (BOOL) hasHostname;
- (BOOL) hasPort;
- (BOOL) hasMethod;
- (BOOL) hasUri;
- (BOOL) hasTransportProtocol;
- (BOOL) hasTransportProtocolVersion;
- (BOOL) hasScheme;
- (BOOL) hasDatacenter;
- (BOOL) hasExpiry;
@property (readonly, retain) NSString* hostname;
@property (readonly) int32_t port;
@property (readonly, retain) NSString* method;
@property (readonly, retain) NSString* uri;
@property (readonly, retain) NSString* transportProtocol;
@property (readonly, retain) NSString* transportProtocolVersion;
@property (readonly, retain) NSString* scheme;
@property (readonly, retain) NSString* datacenter;
@property (readonly) int64_t expiry;
- (NSArray*) headersList;
- (NameValuePair*) headersAtIndex:(int32_t) index;

+ (HostInfo*) defaultInstance;
- (HostInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HostInfo_Builder*) builder;
+ (HostInfo_Builder*) builder;
+ (HostInfo_Builder*) builderWithPrototype:(HostInfo*) prototype;

+ (HostInfo*) parseFromData:(NSData*) data;
+ (HostInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostInfo*) parseFromInputStream:(NSInputStream*) input;
+ (HostInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (HostInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HostInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HostInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HostInfo_Builder : PBGeneratedMessage_Builder {
@private
  HostInfo* result;
}

- (HostInfo*) defaultInstance;

- (HostInfo_Builder*) clear;
- (HostInfo_Builder*) clone;

- (HostInfo*) build;
- (HostInfo*) buildPartial;

- (HostInfo_Builder*) mergeFrom:(HostInfo*) other;
- (HostInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HostInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHostname;
- (NSString*) hostname;
- (HostInfo_Builder*) setHostname:(NSString*) value;
- (HostInfo_Builder*) clearHostname;

- (BOOL) hasPort;
- (int32_t) port;
- (HostInfo_Builder*) setPort:(int32_t) value;
- (HostInfo_Builder*) clearPort;

- (BOOL) hasMethod;
- (NSString*) method;
- (HostInfo_Builder*) setMethod:(NSString*) value;
- (HostInfo_Builder*) clearMethod;

- (BOOL) hasUri;
- (NSString*) uri;
- (HostInfo_Builder*) setUri:(NSString*) value;
- (HostInfo_Builder*) clearUri;

- (BOOL) hasTransportProtocol;
- (NSString*) transportProtocol;
- (HostInfo_Builder*) setTransportProtocol:(NSString*) value;
- (HostInfo_Builder*) clearTransportProtocol;

- (BOOL) hasTransportProtocolVersion;
- (NSString*) transportProtocolVersion;
- (HostInfo_Builder*) setTransportProtocolVersion:(NSString*) value;
- (HostInfo_Builder*) clearTransportProtocolVersion;

- (BOOL) hasScheme;
- (NSString*) scheme;
- (HostInfo_Builder*) setScheme:(NSString*) value;
- (HostInfo_Builder*) clearScheme;

- (NSArray*) headersList;
- (NameValuePair*) headersAtIndex:(int32_t) index;
- (HostInfo_Builder*) replaceHeadersAtIndex:(int32_t) index with:(NameValuePair*) value;
- (HostInfo_Builder*) addHeaders:(NameValuePair*) value;
- (HostInfo_Builder*) addAllHeaders:(NSArray*) values;
- (HostInfo_Builder*) clearHeadersList;

- (BOOL) hasDatacenter;
- (NSString*) datacenter;
- (HostInfo_Builder*) setDatacenter:(NSString*) value;
- (HostInfo_Builder*) clearDatacenter;

- (BOOL) hasExpiry;
- (int64_t) expiry;
- (HostInfo_Builder*) setExpiry:(int64_t) value;
- (HostInfo_Builder*) clearExpiry;
@end

@interface ErrorResponse : PBGeneratedMessage {
@private
  BOOL hasErrorCode_:1;
  BOOL hasDomain_:1;
  BOOL hasErrorDescription_:1;
  int32_t errorCode;
  NSString* domain;
  NSString* errorDescription;
  NSMutableArray* mutableUnderlyingErrorsList;
  NSMutableArray* mutableNameValuePairList;
}
- (BOOL) hasDomain;
- (BOOL) hasErrorCode;
- (BOOL) hasErrorDescription;
@property (readonly, retain) NSString* domain;
@property (readonly) int32_t errorCode;
@property (readonly, retain) NSString* errorDescription;
- (NSArray*) underlyingErrorsList;
- (ErrorResponse*) underlyingErrorsAtIndex:(int32_t) index;
- (NSArray*) nameValuePairList;
- (NameValuePair*) nameValuePairAtIndex:(int32_t) index;

+ (ErrorResponse*) defaultInstance;
- (ErrorResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ErrorResponse_Builder*) builder;
+ (ErrorResponse_Builder*) builder;
+ (ErrorResponse_Builder*) builderWithPrototype:(ErrorResponse*) prototype;

+ (ErrorResponse*) parseFromData:(NSData*) data;
+ (ErrorResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ErrorResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ErrorResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ErrorResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ErrorResponse_Builder : PBGeneratedMessage_Builder {
@private
  ErrorResponse* result;
}

- (ErrorResponse*) defaultInstance;

- (ErrorResponse_Builder*) clear;
- (ErrorResponse_Builder*) clone;

- (ErrorResponse*) build;
- (ErrorResponse*) buildPartial;

- (ErrorResponse_Builder*) mergeFrom:(ErrorResponse*) other;
- (ErrorResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ErrorResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDomain;
- (NSString*) domain;
- (ErrorResponse_Builder*) setDomain:(NSString*) value;
- (ErrorResponse_Builder*) clearDomain;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (ErrorResponse_Builder*) setErrorCode:(int32_t) value;
- (ErrorResponse_Builder*) clearErrorCode;

- (BOOL) hasErrorDescription;
- (NSString*) errorDescription;
- (ErrorResponse_Builder*) setErrorDescription:(NSString*) value;
- (ErrorResponse_Builder*) clearErrorDescription;

- (NSArray*) underlyingErrorsList;
- (ErrorResponse*) underlyingErrorsAtIndex:(int32_t) index;
- (ErrorResponse_Builder*) replaceUnderlyingErrorsAtIndex:(int32_t) index with:(ErrorResponse*) value;
- (ErrorResponse_Builder*) addUnderlyingErrors:(ErrorResponse*) value;
- (ErrorResponse_Builder*) addAllUnderlyingErrors:(NSArray*) values;
- (ErrorResponse_Builder*) clearUnderlyingErrorsList;

- (NSArray*) nameValuePairList;
- (NameValuePair*) nameValuePairAtIndex:(int32_t) index;
- (ErrorResponse_Builder*) replaceNameValuePairAtIndex:(int32_t) index with:(NameValuePair*) value;
- (ErrorResponse_Builder*) addNameValuePair:(NameValuePair*) value;
- (ErrorResponse_Builder*) addAllNameValuePair:(NSArray*) values;
- (ErrorResponse_Builder*) clearNameValuePairList;
@end

@interface FileError : PBGeneratedMessage {
@private
  BOOL hasErrorResponse_:1;
  BOOL hasFileChecksum_:1;
  ErrorResponse* errorResponse;
  NSData* fileChecksum;
}
- (BOOL) hasFileChecksum;
- (BOOL) hasErrorResponse;
@property (readonly, retain) NSData* fileChecksum;
@property (readonly, retain) ErrorResponse* errorResponse;

+ (FileError*) defaultInstance;
- (FileError*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileError_Builder*) builder;
+ (FileError_Builder*) builder;
+ (FileError_Builder*) builderWithPrototype:(FileError*) prototype;

+ (FileError*) parseFromData:(NSData*) data;
+ (FileError*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileError*) parseFromInputStream:(NSInputStream*) input;
+ (FileError*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileError*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileError*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileError*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileError_Builder : PBGeneratedMessage_Builder {
@private
  FileError* result;
}

- (FileError*) defaultInstance;

- (FileError_Builder*) clear;
- (FileError_Builder*) clone;

- (FileError*) build;
- (FileError*) buildPartial;

- (FileError_Builder*) mergeFrom:(FileError*) other;
- (FileError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileChecksum;
- (NSData*) fileChecksum;
- (FileError_Builder*) setFileChecksum:(NSData*) value;
- (FileError_Builder*) clearFileChecksum;

- (BOOL) hasErrorResponse;
- (ErrorResponse*) errorResponse;
- (FileError_Builder*) setErrorResponse:(ErrorResponse*) value;
- (FileError_Builder*) setErrorResponseBuilder:(ErrorResponse_Builder*) builderForValue;
- (FileError_Builder*) mergeErrorResponse:(ErrorResponse*) value;
- (FileError_Builder*) clearErrorResponse;
@end

@interface ChunkError : PBGeneratedMessage {
@private
  BOOL hasErrorResponse_:1;
  BOOL hasChunkChecksum_:1;
  ErrorResponse* errorResponse;
  NSData* chunkChecksum;
}
- (BOOL) hasChunkChecksum;
- (BOOL) hasErrorResponse;
@property (readonly, retain) NSData* chunkChecksum;
@property (readonly, retain) ErrorResponse* errorResponse;

+ (ChunkError*) defaultInstance;
- (ChunkError*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChunkError_Builder*) builder;
+ (ChunkError_Builder*) builder;
+ (ChunkError_Builder*) builderWithPrototype:(ChunkError*) prototype;

+ (ChunkError*) parseFromData:(NSData*) data;
+ (ChunkError*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkError*) parseFromInputStream:(NSInputStream*) input;
+ (ChunkError*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ChunkError*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkError*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChunkError*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChunkError_Builder : PBGeneratedMessage_Builder {
@private
  ChunkError* result;
}

- (ChunkError*) defaultInstance;

- (ChunkError_Builder*) clear;
- (ChunkError_Builder*) clone;

- (ChunkError*) build;
- (ChunkError*) buildPartial;

- (ChunkError_Builder*) mergeFrom:(ChunkError*) other;
- (ChunkError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChunkError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChunkChecksum;
- (NSData*) chunkChecksum;
- (ChunkError_Builder*) setChunkChecksum:(NSData*) value;
- (ChunkError_Builder*) clearChunkChecksum;

- (BOOL) hasErrorResponse;
- (ErrorResponse*) errorResponse;
- (ChunkError_Builder*) setErrorResponse:(ErrorResponse*) value;
- (ChunkError_Builder*) setErrorResponseBuilder:(ErrorResponse_Builder*) builderForValue;
- (ChunkError_Builder*) mergeErrorResponse:(ErrorResponse*) value;
- (ChunkError_Builder*) clearErrorResponse;
@end

@interface ChunkErrorIndex : PBGeneratedMessage {
@private
  BOOL hasErrorResponse_:1;
  BOOL hasChunkChecksum_:1;
  BOOL hasChunkIndex_:1;
  ErrorResponse* errorResponse;
  NSData* chunkChecksum;
  int32_t chunkIndex;
}
- (BOOL) hasChunkChecksum;
- (BOOL) hasErrorResponse;
- (BOOL) hasChunkIndex;
@property (readonly, retain) NSData* chunkChecksum;
@property (readonly, retain) ErrorResponse* errorResponse;
@property (readonly) int32_t chunkIndex;

+ (ChunkErrorIndex*) defaultInstance;
- (ChunkErrorIndex*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChunkErrorIndex_Builder*) builder;
+ (ChunkErrorIndex_Builder*) builder;
+ (ChunkErrorIndex_Builder*) builderWithPrototype:(ChunkErrorIndex*) prototype;

+ (ChunkErrorIndex*) parseFromData:(NSData*) data;
+ (ChunkErrorIndex*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkErrorIndex*) parseFromInputStream:(NSInputStream*) input;
+ (ChunkErrorIndex*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ChunkErrorIndex*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkErrorIndex*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChunkErrorIndex*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChunkErrorIndex_Builder : PBGeneratedMessage_Builder {
@private
  ChunkErrorIndex* result;
}

- (ChunkErrorIndex*) defaultInstance;

- (ChunkErrorIndex_Builder*) clear;
- (ChunkErrorIndex_Builder*) clone;

- (ChunkErrorIndex*) build;
- (ChunkErrorIndex*) buildPartial;

- (ChunkErrorIndex_Builder*) mergeFrom:(ChunkErrorIndex*) other;
- (ChunkErrorIndex_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChunkErrorIndex_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChunkChecksum;
- (NSData*) chunkChecksum;
- (ChunkErrorIndex_Builder*) setChunkChecksum:(NSData*) value;
- (ChunkErrorIndex_Builder*) clearChunkChecksum;

- (BOOL) hasErrorResponse;
- (ErrorResponse*) errorResponse;
- (ChunkErrorIndex_Builder*) setErrorResponse:(ErrorResponse*) value;
- (ChunkErrorIndex_Builder*) setErrorResponseBuilder:(ErrorResponse_Builder*) builderForValue;
- (ChunkErrorIndex_Builder*) mergeErrorResponse:(ErrorResponse*) value;
- (ChunkErrorIndex_Builder*) clearErrorResponse;

- (BOOL) hasChunkIndex;
- (int32_t) chunkIndex;
- (ChunkErrorIndex_Builder*) setChunkIndex:(int32_t) value;
- (ChunkErrorIndex_Builder*) clearChunkIndex;
@end

@interface FileChunkError : PBGeneratedMessage {
@private
  BOOL hasFileChecksum_:1;
  NSData* fileChecksum;
  NSMutableArray* mutableChunkErrorList;
}
- (BOOL) hasFileChecksum;
@property (readonly, retain) NSData* fileChecksum;
- (NSArray*) chunkErrorList;
- (ChunkErrorIndex*) chunkErrorAtIndex:(int32_t) index;

+ (FileChunkError*) defaultInstance;
- (FileChunkError*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChunkError_Builder*) builder;
+ (FileChunkError_Builder*) builder;
+ (FileChunkError_Builder*) builderWithPrototype:(FileChunkError*) prototype;

+ (FileChunkError*) parseFromData:(NSData*) data;
+ (FileChunkError*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkError*) parseFromInputStream:(NSInputStream*) input;
+ (FileChunkError*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChunkError*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkError*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChunkError*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChunkError_Builder : PBGeneratedMessage_Builder {
@private
  FileChunkError* result;
}

- (FileChunkError*) defaultInstance;

- (FileChunkError_Builder*) clear;
- (FileChunkError_Builder*) clone;

- (FileChunkError*) build;
- (FileChunkError*) buildPartial;

- (FileChunkError_Builder*) mergeFrom:(FileChunkError*) other;
- (FileChunkError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChunkError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileChecksum;
- (NSData*) fileChecksum;
- (FileChunkError_Builder*) setFileChecksum:(NSData*) value;
- (FileChunkError_Builder*) clearFileChecksum;

- (NSArray*) chunkErrorList;
- (ChunkErrorIndex*) chunkErrorAtIndex:(int32_t) index;
- (FileChunkError_Builder*) replaceChunkErrorAtIndex:(int32_t) index with:(ChunkErrorIndex*) value;
- (FileChunkError_Builder*) addChunkError:(ChunkErrorIndex*) value;
- (FileChunkError_Builder*) addAllChunkError:(NSArray*) values;
- (FileChunkError_Builder*) clearChunkErrorList;
@end

@interface StorageContainerError : PBGeneratedMessage {
@private
  BOOL hasStorageContainerKey_:1;
  BOOL hasErrorResponse_:1;
  NSString* storageContainerKey;
  ErrorResponse* errorResponse;
}
- (BOOL) hasStorageContainerKey;
- (BOOL) hasErrorResponse;
@property (readonly, retain) NSString* storageContainerKey;
@property (readonly, retain) ErrorResponse* errorResponse;

+ (StorageContainerError*) defaultInstance;
- (StorageContainerError*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageContainerError_Builder*) builder;
+ (StorageContainerError_Builder*) builder;
+ (StorageContainerError_Builder*) builderWithPrototype:(StorageContainerError*) prototype;

+ (StorageContainerError*) parseFromData:(NSData*) data;
+ (StorageContainerError*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerError*) parseFromInputStream:(NSInputStream*) input;
+ (StorageContainerError*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageContainerError*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerError*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageContainerError*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageContainerError_Builder : PBGeneratedMessage_Builder {
@private
  StorageContainerError* result;
}

- (StorageContainerError*) defaultInstance;

- (StorageContainerError_Builder*) clear;
- (StorageContainerError_Builder*) clone;

- (StorageContainerError*) build;
- (StorageContainerError*) buildPartial;

- (StorageContainerError_Builder*) mergeFrom:(StorageContainerError*) other;
- (StorageContainerError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageContainerError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStorageContainerKey;
- (NSString*) storageContainerKey;
- (StorageContainerError_Builder*) setStorageContainerKey:(NSString*) value;
- (StorageContainerError_Builder*) clearStorageContainerKey;

- (BOOL) hasErrorResponse;
- (ErrorResponse*) errorResponse;
- (StorageContainerError_Builder*) setErrorResponse:(ErrorResponse*) value;
- (StorageContainerError_Builder*) setErrorResponseBuilder:(ErrorResponse_Builder*) builderForValue;
- (StorageContainerError_Builder*) mergeErrorResponse:(ErrorResponse*) value;
- (StorageContainerError_Builder*) clearErrorResponse;
@end

@interface MethodCompletionInfo : PBGeneratedMessage {
@private
  BOOL hasUrl_:1;
  BOOL hasResponseStatusLine_:1;
  BOOL hasStorageContainerAuthorizationToken_:1;
  BOOL hasError_:1;
  BOOL hasResponseBody_:1;
  BOOL hasClientComputedMd5_:1;
  BOOL hasResponseStatusCode_:1;
  NSString* url;
  NSString* responseStatusLine;
  NSString* storageContainerAuthorizationToken;
  ErrorResponse* error;
  NSData* responseBody;
  NSData* clientComputedMd5;
  int32_t responseStatusCode;
  NSMutableArray* mutableVendorResponseHeadersList;
  NSMutableArray* mutableVendorNvPairsList;
  NSMutableArray* mutableClientNvPairsList;
}
- (BOOL) hasUrl;
- (BOOL) hasResponseStatusCode;
- (BOOL) hasResponseStatusLine;
- (BOOL) hasResponseBody;
- (BOOL) hasError;
- (BOOL) hasClientComputedMd5;
- (BOOL) hasStorageContainerAuthorizationToken;
@property (readonly, retain) NSString* url;
@property (readonly) int32_t responseStatusCode;
@property (readonly, retain) NSString* responseStatusLine;
@property (readonly, retain) NSData* responseBody;
@property (readonly, retain) ErrorResponse* error;
@property (readonly, retain) NSData* clientComputedMd5;
@property (readonly, retain) NSString* storageContainerAuthorizationToken;
- (NSArray*) vendorResponseHeadersList;
- (NameValuePair*) vendorResponseHeadersAtIndex:(int32_t) index;
- (NSArray*) vendorNvPairsList;
- (NameValuePair*) vendorNvPairsAtIndex:(int32_t) index;
- (NSArray*) clientNvPairsList;
- (NameValuePair*) clientNvPairsAtIndex:(int32_t) index;

+ (MethodCompletionInfo*) defaultInstance;
- (MethodCompletionInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MethodCompletionInfo_Builder*) builder;
+ (MethodCompletionInfo_Builder*) builder;
+ (MethodCompletionInfo_Builder*) builderWithPrototype:(MethodCompletionInfo*) prototype;

+ (MethodCompletionInfo*) parseFromData:(NSData*) data;
+ (MethodCompletionInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodCompletionInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MethodCompletionInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MethodCompletionInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodCompletionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MethodCompletionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MethodCompletionInfo_Builder : PBGeneratedMessage_Builder {
@private
  MethodCompletionInfo* result;
}

- (MethodCompletionInfo*) defaultInstance;

- (MethodCompletionInfo_Builder*) clear;
- (MethodCompletionInfo_Builder*) clone;

- (MethodCompletionInfo*) build;
- (MethodCompletionInfo*) buildPartial;

- (MethodCompletionInfo_Builder*) mergeFrom:(MethodCompletionInfo*) other;
- (MethodCompletionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MethodCompletionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUrl;
- (NSString*) url;
- (MethodCompletionInfo_Builder*) setUrl:(NSString*) value;
- (MethodCompletionInfo_Builder*) clearUrl;

- (BOOL) hasResponseStatusCode;
- (int32_t) responseStatusCode;
- (MethodCompletionInfo_Builder*) setResponseStatusCode:(int32_t) value;
- (MethodCompletionInfo_Builder*) clearResponseStatusCode;

- (BOOL) hasResponseStatusLine;
- (NSString*) responseStatusLine;
- (MethodCompletionInfo_Builder*) setResponseStatusLine:(NSString*) value;
- (MethodCompletionInfo_Builder*) clearResponseStatusLine;

- (NSArray*) vendorResponseHeadersList;
- (NameValuePair*) vendorResponseHeadersAtIndex:(int32_t) index;
- (MethodCompletionInfo_Builder*) replaceVendorResponseHeadersAtIndex:(int32_t) index with:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addVendorResponseHeaders:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addAllVendorResponseHeaders:(NSArray*) values;
- (MethodCompletionInfo_Builder*) clearVendorResponseHeadersList;

- (BOOL) hasResponseBody;
- (NSData*) responseBody;
- (MethodCompletionInfo_Builder*) setResponseBody:(NSData*) value;
- (MethodCompletionInfo_Builder*) clearResponseBody;

- (BOOL) hasError;
- (ErrorResponse*) error;
- (MethodCompletionInfo_Builder*) setError:(ErrorResponse*) value;
- (MethodCompletionInfo_Builder*) setErrorBuilder:(ErrorResponse_Builder*) builderForValue;
- (MethodCompletionInfo_Builder*) mergeError:(ErrorResponse*) value;
- (MethodCompletionInfo_Builder*) clearError;

- (BOOL) hasClientComputedMd5;
- (NSData*) clientComputedMd5;
- (MethodCompletionInfo_Builder*) setClientComputedMd5:(NSData*) value;
- (MethodCompletionInfo_Builder*) clearClientComputedMd5;

- (NSArray*) vendorNvPairsList;
- (NameValuePair*) vendorNvPairsAtIndex:(int32_t) index;
- (MethodCompletionInfo_Builder*) replaceVendorNvPairsAtIndex:(int32_t) index with:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addVendorNvPairs:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addAllVendorNvPairs:(NSArray*) values;
- (MethodCompletionInfo_Builder*) clearVendorNvPairsList;

- (NSArray*) clientNvPairsList;
- (NameValuePair*) clientNvPairsAtIndex:(int32_t) index;
- (MethodCompletionInfo_Builder*) replaceClientNvPairsAtIndex:(int32_t) index with:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addClientNvPairs:(NameValuePair*) value;
- (MethodCompletionInfo_Builder*) addAllClientNvPairs:(NSArray*) values;
- (MethodCompletionInfo_Builder*) clearClientNvPairsList;

- (BOOL) hasStorageContainerAuthorizationToken;
- (NSString*) storageContainerAuthorizationToken;
- (MethodCompletionInfo_Builder*) setStorageContainerAuthorizationToken:(NSString*) value;
- (MethodCompletionInfo_Builder*) clearStorageContainerAuthorizationToken;
@end

@interface MethodCompletionInfoList : PBGeneratedMessage {
@private
  NSMutableArray* mutableMethodCompletionInfoList;
}
- (NSArray*) methodCompletionInfoList;
- (MethodCompletionInfo*) methodCompletionInfoAtIndex:(int32_t) index;

+ (MethodCompletionInfoList*) defaultInstance;
- (MethodCompletionInfoList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MethodCompletionInfoList_Builder*) builder;
+ (MethodCompletionInfoList_Builder*) builder;
+ (MethodCompletionInfoList_Builder*) builderWithPrototype:(MethodCompletionInfoList*) prototype;

+ (MethodCompletionInfoList*) parseFromData:(NSData*) data;
+ (MethodCompletionInfoList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodCompletionInfoList*) parseFromInputStream:(NSInputStream*) input;
+ (MethodCompletionInfoList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MethodCompletionInfoList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodCompletionInfoList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MethodCompletionInfoList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MethodCompletionInfoList_Builder : PBGeneratedMessage_Builder {
@private
  MethodCompletionInfoList* result;
}

- (MethodCompletionInfoList*) defaultInstance;

- (MethodCompletionInfoList_Builder*) clear;
- (MethodCompletionInfoList_Builder*) clone;

- (MethodCompletionInfoList*) build;
- (MethodCompletionInfoList*) buildPartial;

- (MethodCompletionInfoList_Builder*) mergeFrom:(MethodCompletionInfoList*) other;
- (MethodCompletionInfoList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MethodCompletionInfoList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) methodCompletionInfoList;
- (MethodCompletionInfo*) methodCompletionInfoAtIndex:(int32_t) index;
- (MethodCompletionInfoList_Builder*) replaceMethodCompletionInfoAtIndex:(int32_t) index with:(MethodCompletionInfo*) value;
- (MethodCompletionInfoList_Builder*) addMethodCompletionInfo:(MethodCompletionInfo*) value;
- (MethodCompletionInfoList_Builder*) addAllMethodCompletionInfo:(NSArray*) values;
- (MethodCompletionInfoList_Builder*) clearMethodCompletionInfoList;
@end

@interface FileChunkList : PBGeneratedMessage {
@private
  BOOL hasAuthorization_:1;
  BOOL hasFileChecksum_:1;
  NSString* authorization;
  NSData* fileChecksum;
  NSMutableArray* mutableChunkInfoList;
}
- (BOOL) hasFileChecksum;
- (BOOL) hasAuthorization;
@property (readonly, retain) NSData* fileChecksum;
@property (readonly, retain) NSString* authorization;
- (NSArray*) chunkInfoList;
- (ChunkInfo*) chunkInfoAtIndex:(int32_t) index;

+ (FileChunkList*) defaultInstance;
- (FileChunkList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChunkList_Builder*) builder;
+ (FileChunkList_Builder*) builder;
+ (FileChunkList_Builder*) builderWithPrototype:(FileChunkList*) prototype;

+ (FileChunkList*) parseFromData:(NSData*) data;
+ (FileChunkList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkList*) parseFromInputStream:(NSInputStream*) input;
+ (FileChunkList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChunkList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChunkList_Builder : PBGeneratedMessage_Builder {
@private
  FileChunkList* result;
}

- (FileChunkList*) defaultInstance;

- (FileChunkList_Builder*) clear;
- (FileChunkList_Builder*) clone;

- (FileChunkList*) build;
- (FileChunkList*) buildPartial;

- (FileChunkList_Builder*) mergeFrom:(FileChunkList*) other;
- (FileChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileChecksum;
- (NSData*) fileChecksum;
- (FileChunkList_Builder*) setFileChecksum:(NSData*) value;
- (FileChunkList_Builder*) clearFileChecksum;

- (BOOL) hasAuthorization;
- (NSString*) authorization;
- (FileChunkList_Builder*) setAuthorization:(NSString*) value;
- (FileChunkList_Builder*) clearAuthorization;

- (NSArray*) chunkInfoList;
- (ChunkInfo*) chunkInfoAtIndex:(int32_t) index;
- (FileChunkList_Builder*) replaceChunkInfoAtIndex:(int32_t) index with:(ChunkInfo*) value;
- (FileChunkList_Builder*) addChunkInfo:(ChunkInfo*) value;
- (FileChunkList_Builder*) addAllChunkInfo:(NSArray*) values;
- (FileChunkList_Builder*) clearChunkInfoList;
@end

@interface FileChunkLists : PBGeneratedMessage {
@private
  NSMutableArray* mutableFileChunkListList;
}
- (NSArray*) fileChunkListList;
- (FileChunkList*) fileChunkListAtIndex:(int32_t) index;

+ (FileChunkLists*) defaultInstance;
- (FileChunkLists*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChunkLists_Builder*) builder;
+ (FileChunkLists_Builder*) builder;
+ (FileChunkLists_Builder*) builderWithPrototype:(FileChunkLists*) prototype;

+ (FileChunkLists*) parseFromData:(NSData*) data;
+ (FileChunkLists*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkLists*) parseFromInputStream:(NSInputStream*) input;
+ (FileChunkLists*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChunkLists*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChunkLists_Builder : PBGeneratedMessage_Builder {
@private
  FileChunkLists* result;
}

- (FileChunkLists*) defaultInstance;

- (FileChunkLists_Builder*) clear;
- (FileChunkLists_Builder*) clone;

- (FileChunkLists*) build;
- (FileChunkLists*) buildPartial;

- (FileChunkLists_Builder*) mergeFrom:(FileChunkLists*) other;
- (FileChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) fileChunkListList;
- (FileChunkList*) fileChunkListAtIndex:(int32_t) index;
- (FileChunkLists_Builder*) replaceFileChunkListAtIndex:(int32_t) index with:(FileChunkList*) value;
- (FileChunkLists_Builder*) addFileChunkList:(FileChunkList*) value;
- (FileChunkLists_Builder*) addAllFileChunkList:(NSArray*) values;
- (FileChunkLists_Builder*) clearFileChunkListList;
@end

@interface StorageContainerChunkList : PBGeneratedMessage {
@private
  BOOL hasStorageContainerAuthorizationToken_:1;
  BOOL hasHostInfo_:1;
  BOOL hasStorageContainerKey_:1;
  NSString* storageContainerAuthorizationToken;
  HostInfo* hostInfo;
  NSData* storageContainerKey;
  NSMutableArray* mutableChunkChecksumList;
}
- (BOOL) hasStorageContainerKey;
- (BOOL) hasHostInfo;
- (BOOL) hasStorageContainerAuthorizationToken;
@property (readonly, retain) NSData* storageContainerKey;
@property (readonly, retain) HostInfo* hostInfo;
@property (readonly, retain) NSString* storageContainerAuthorizationToken;
- (NSArray*) chunkChecksumList;
- (NSData*) chunkChecksumAtIndex:(int32_t) index;

+ (StorageContainerChunkList*) defaultInstance;
- (StorageContainerChunkList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageContainerChunkList_Builder*) builder;
+ (StorageContainerChunkList_Builder*) builder;
+ (StorageContainerChunkList_Builder*) builderWithPrototype:(StorageContainerChunkList*) prototype;

+ (StorageContainerChunkList*) parseFromData:(NSData*) data;
+ (StorageContainerChunkList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerChunkList*) parseFromInputStream:(NSInputStream*) input;
+ (StorageContainerChunkList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageContainerChunkList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageContainerChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageContainerChunkList_Builder : PBGeneratedMessage_Builder {
@private
  StorageContainerChunkList* result;
}

- (StorageContainerChunkList*) defaultInstance;

- (StorageContainerChunkList_Builder*) clear;
- (StorageContainerChunkList_Builder*) clone;

- (StorageContainerChunkList*) build;
- (StorageContainerChunkList*) buildPartial;

- (StorageContainerChunkList_Builder*) mergeFrom:(StorageContainerChunkList*) other;
- (StorageContainerChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageContainerChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStorageContainerKey;
- (NSData*) storageContainerKey;
- (StorageContainerChunkList_Builder*) setStorageContainerKey:(NSData*) value;
- (StorageContainerChunkList_Builder*) clearStorageContainerKey;

- (BOOL) hasHostInfo;
- (HostInfo*) hostInfo;
- (StorageContainerChunkList_Builder*) setHostInfo:(HostInfo*) value;
- (StorageContainerChunkList_Builder*) setHostInfoBuilder:(HostInfo_Builder*) builderForValue;
- (StorageContainerChunkList_Builder*) mergeHostInfo:(HostInfo*) value;
- (StorageContainerChunkList_Builder*) clearHostInfo;

- (NSArray*) chunkChecksumList;
- (NSData*) chunkChecksumAtIndex:(int32_t) index;
- (StorageContainerChunkList_Builder*) replaceChunkChecksumAtIndex:(int32_t) index with:(NSData*) value;
- (StorageContainerChunkList_Builder*) addChunkChecksum:(NSData*) value;
- (StorageContainerChunkList_Builder*) addAllChunkChecksum:(NSArray*) values;
- (StorageContainerChunkList_Builder*) clearChunkChecksumList;

- (BOOL) hasStorageContainerAuthorizationToken;
- (NSString*) storageContainerAuthorizationToken;
- (StorageContainerChunkList_Builder*) setStorageContainerAuthorizationToken:(NSString*) value;
- (StorageContainerChunkList_Builder*) clearStorageContainerAuthorizationToken;
@end

@interface StorageContainerChunkLists : PBGeneratedMessage {
@private
  BOOL hasVerbosityLevel_:1;
  int32_t verbosityLevel;
  NSMutableArray* mutableStorageContainerChunkListList;
  NSMutableArray* mutableFileErrorList;
}
- (BOOL) hasVerbosityLevel;
@property (readonly) int32_t verbosityLevel;
- (NSArray*) storageContainerChunkListList;
- (StorageContainerChunkList*) storageContainerChunkListAtIndex:(int32_t) index;
- (NSArray*) fileErrorList;
- (FileError*) fileErrorAtIndex:(int32_t) index;

+ (StorageContainerChunkLists*) defaultInstance;
- (StorageContainerChunkLists*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageContainerChunkLists_Builder*) builder;
+ (StorageContainerChunkLists_Builder*) builder;
+ (StorageContainerChunkLists_Builder*) builderWithPrototype:(StorageContainerChunkLists*) prototype;

+ (StorageContainerChunkLists*) parseFromData:(NSData*) data;
+ (StorageContainerChunkLists*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerChunkLists*) parseFromInputStream:(NSInputStream*) input;
+ (StorageContainerChunkLists*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageContainerChunkLists*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageContainerChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageContainerChunkLists_Builder : PBGeneratedMessage_Builder {
@private
  StorageContainerChunkLists* result;
}

- (StorageContainerChunkLists*) defaultInstance;

- (StorageContainerChunkLists_Builder*) clear;
- (StorageContainerChunkLists_Builder*) clone;

- (StorageContainerChunkLists*) build;
- (StorageContainerChunkLists*) buildPartial;

- (StorageContainerChunkLists_Builder*) mergeFrom:(StorageContainerChunkLists*) other;
- (StorageContainerChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageContainerChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) storageContainerChunkListList;
- (StorageContainerChunkList*) storageContainerChunkListAtIndex:(int32_t) index;
- (StorageContainerChunkLists_Builder*) replaceStorageContainerChunkListAtIndex:(int32_t) index with:(StorageContainerChunkList*) value;
- (StorageContainerChunkLists_Builder*) addStorageContainerChunkList:(StorageContainerChunkList*) value;
- (StorageContainerChunkLists_Builder*) addAllStorageContainerChunkList:(NSArray*) values;
- (StorageContainerChunkLists_Builder*) clearStorageContainerChunkListList;

- (NSArray*) fileErrorList;
- (FileError*) fileErrorAtIndex:(int32_t) index;
- (StorageContainerChunkLists_Builder*) replaceFileErrorAtIndex:(int32_t) index with:(FileError*) value;
- (StorageContainerChunkLists_Builder*) addFileError:(FileError*) value;
- (StorageContainerChunkLists_Builder*) addAllFileError:(NSArray*) values;
- (StorageContainerChunkLists_Builder*) clearFileErrorList;

- (BOOL) hasVerbosityLevel;
- (int32_t) verbosityLevel;
- (StorageContainerChunkLists_Builder*) setVerbosityLevel:(int32_t) value;
- (StorageContainerChunkLists_Builder*) clearVerbosityLevel;
@end

@interface StorageContainerErrorList : PBGeneratedMessage {
@private
  NSMutableArray* mutableStorageContainerErrorList;
}
- (NSArray*) storageContainerErrorList;
- (StorageContainerError*) storageContainerErrorAtIndex:(int32_t) index;

+ (StorageContainerErrorList*) defaultInstance;
- (StorageContainerErrorList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageContainerErrorList_Builder*) builder;
+ (StorageContainerErrorList_Builder*) builder;
+ (StorageContainerErrorList_Builder*) builderWithPrototype:(StorageContainerErrorList*) prototype;

+ (StorageContainerErrorList*) parseFromData:(NSData*) data;
+ (StorageContainerErrorList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerErrorList*) parseFromInputStream:(NSInputStream*) input;
+ (StorageContainerErrorList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageContainerErrorList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageContainerErrorList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageContainerErrorList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageContainerErrorList_Builder : PBGeneratedMessage_Builder {
@private
  StorageContainerErrorList* result;
}

- (StorageContainerErrorList*) defaultInstance;

- (StorageContainerErrorList_Builder*) clear;
- (StorageContainerErrorList_Builder*) clone;

- (StorageContainerErrorList*) build;
- (StorageContainerErrorList*) buildPartial;

- (StorageContainerErrorList_Builder*) mergeFrom:(StorageContainerErrorList*) other;
- (StorageContainerErrorList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageContainerErrorList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) storageContainerErrorList;
- (StorageContainerError*) storageContainerErrorAtIndex:(int32_t) index;
- (StorageContainerErrorList_Builder*) replaceStorageContainerErrorAtIndex:(int32_t) index with:(StorageContainerError*) value;
- (StorageContainerErrorList_Builder*) addStorageContainerError:(StorageContainerError*) value;
- (StorageContainerErrorList_Builder*) addAllStorageContainerError:(NSArray*) values;
- (StorageContainerErrorList_Builder*) clearStorageContainerErrorList;
@end

@interface FileChecksumAuthorization : PBGeneratedMessage {
@private
  BOOL hasAuthorization_:1;
  BOOL hasFileChecksum_:1;
  NSString* authorization;
  NSData* fileChecksum;
  NSMutableArray* mutableChunkChecksumsList;
}
- (BOOL) hasFileChecksum;
- (BOOL) hasAuthorization;
@property (readonly, retain) NSData* fileChecksum;
@property (readonly, retain) NSString* authorization;
- (NSArray*) chunkChecksumsList;
- (NSData*) chunkChecksumsAtIndex:(int32_t) index;

+ (FileChecksumAuthorization*) defaultInstance;
- (FileChecksumAuthorization*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChecksumAuthorization_Builder*) builder;
+ (FileChecksumAuthorization_Builder*) builder;
+ (FileChecksumAuthorization_Builder*) builderWithPrototype:(FileChecksumAuthorization*) prototype;

+ (FileChecksumAuthorization*) parseFromData:(NSData*) data;
+ (FileChecksumAuthorization*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumAuthorization*) parseFromInputStream:(NSInputStream*) input;
+ (FileChecksumAuthorization*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChecksumAuthorization*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumAuthorization*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChecksumAuthorization*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChecksumAuthorization_Builder : PBGeneratedMessage_Builder {
@private
  FileChecksumAuthorization* result;
}

- (FileChecksumAuthorization*) defaultInstance;

- (FileChecksumAuthorization_Builder*) clear;
- (FileChecksumAuthorization_Builder*) clone;

- (FileChecksumAuthorization*) build;
- (FileChecksumAuthorization*) buildPartial;

- (FileChecksumAuthorization_Builder*) mergeFrom:(FileChecksumAuthorization*) other;
- (FileChecksumAuthorization_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChecksumAuthorization_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileChecksum;
- (NSData*) fileChecksum;
- (FileChecksumAuthorization_Builder*) setFileChecksum:(NSData*) value;
- (FileChecksumAuthorization_Builder*) clearFileChecksum;

- (BOOL) hasAuthorization;
- (NSString*) authorization;
- (FileChecksumAuthorization_Builder*) setAuthorization:(NSString*) value;
- (FileChecksumAuthorization_Builder*) clearAuthorization;

- (NSArray*) chunkChecksumsList;
- (NSData*) chunkChecksumsAtIndex:(int32_t) index;
- (FileChecksumAuthorization_Builder*) replaceChunkChecksumsAtIndex:(int32_t) index with:(NSData*) value;
- (FileChecksumAuthorization_Builder*) addChunkChecksums:(NSData*) value;
- (FileChecksumAuthorization_Builder*) addAllChunkChecksums:(NSArray*) values;
- (FileChecksumAuthorization_Builder*) clearChunkChecksumsList;
@end

@interface FileChecksumAuthorizationList : PBGeneratedMessage {
@private
  NSMutableArray* mutableFileChecksumAuthorizationList;
}
- (NSArray*) fileChecksumAuthorizationList;
- (FileChecksumAuthorization*) fileChecksumAuthorizationAtIndex:(int32_t) index;

+ (FileChecksumAuthorizationList*) defaultInstance;
- (FileChecksumAuthorizationList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChecksumAuthorizationList_Builder*) builder;
+ (FileChecksumAuthorizationList_Builder*) builder;
+ (FileChecksumAuthorizationList_Builder*) builderWithPrototype:(FileChecksumAuthorizationList*) prototype;

+ (FileChecksumAuthorizationList*) parseFromData:(NSData*) data;
+ (FileChecksumAuthorizationList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumAuthorizationList*) parseFromInputStream:(NSInputStream*) input;
+ (FileChecksumAuthorizationList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChecksumAuthorizationList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumAuthorizationList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChecksumAuthorizationList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChecksumAuthorizationList_Builder : PBGeneratedMessage_Builder {
@private
  FileChecksumAuthorizationList* result;
}

- (FileChecksumAuthorizationList*) defaultInstance;

- (FileChecksumAuthorizationList_Builder*) clear;
- (FileChecksumAuthorizationList_Builder*) clone;

- (FileChecksumAuthorizationList*) build;
- (FileChecksumAuthorizationList*) buildPartial;

- (FileChecksumAuthorizationList_Builder*) mergeFrom:(FileChecksumAuthorizationList*) other;
- (FileChecksumAuthorizationList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChecksumAuthorizationList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) fileChecksumAuthorizationList;
- (FileChecksumAuthorization*) fileChecksumAuthorizationAtIndex:(int32_t) index;
- (FileChecksumAuthorizationList_Builder*) replaceFileChecksumAuthorizationAtIndex:(int32_t) index with:(FileChecksumAuthorization*) value;
- (FileChecksumAuthorizationList_Builder*) addFileChecksumAuthorization:(FileChecksumAuthorization*) value;
- (FileChecksumAuthorizationList_Builder*) addAllFileChecksumAuthorization:(NSArray*) values;
- (FileChecksumAuthorizationList_Builder*) clearFileChecksumAuthorizationList;
@end

@interface ChunkReference : PBGeneratedMessage {
@private
  BOOL hasContainerIndex_:1;
  BOOL hasChunkIndex_:1;
  int64_t containerIndex;
  int64_t chunkIndex;
}
- (BOOL) hasContainerIndex;
- (BOOL) hasChunkIndex;
@property (readonly) int64_t containerIndex;
@property (readonly) int64_t chunkIndex;

+ (ChunkReference*) defaultInstance;
- (ChunkReference*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChunkReference_Builder*) builder;
+ (ChunkReference_Builder*) builder;
+ (ChunkReference_Builder*) builderWithPrototype:(ChunkReference*) prototype;

+ (ChunkReference*) parseFromData:(NSData*) data;
+ (ChunkReference*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkReference*) parseFromInputStream:(NSInputStream*) input;
+ (ChunkReference*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ChunkReference*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkReference*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChunkReference*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChunkReference_Builder : PBGeneratedMessage_Builder {
@private
  ChunkReference* result;
}

- (ChunkReference*) defaultInstance;

- (ChunkReference_Builder*) clear;
- (ChunkReference_Builder*) clone;

- (ChunkReference*) build;
- (ChunkReference*) buildPartial;

- (ChunkReference_Builder*) mergeFrom:(ChunkReference*) other;
- (ChunkReference_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChunkReference_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContainerIndex;
- (int64_t) containerIndex;
- (ChunkReference_Builder*) setContainerIndex:(int64_t) value;
- (ChunkReference_Builder*) clearContainerIndex;

- (BOOL) hasChunkIndex;
- (int64_t) chunkIndex;
- (ChunkReference_Builder*) setChunkIndex:(int64_t) value;
- (ChunkReference_Builder*) clearChunkIndex;
@end

@interface FileChecksumChunkReferences : PBGeneratedMessage {
@private
  BOOL hasFileChecksum_:1;
  BOOL hasFileSignature_:1;
  NSData* fileChecksum;
  NSData* fileSignature;
  NSMutableArray* mutableChunkReferencesList;
}
- (BOOL) hasFileChecksum;
- (BOOL) hasFileSignature;
@property (readonly, retain) NSData* fileChecksum;
@property (readonly, retain) NSData* fileSignature;
- (NSArray*) chunkReferencesList;
- (ChunkReference*) chunkReferencesAtIndex:(int32_t) index;

+ (FileChecksumChunkReferences*) defaultInstance;
- (FileChecksumChunkReferences*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChecksumChunkReferences_Builder*) builder;
+ (FileChecksumChunkReferences_Builder*) builder;
+ (FileChecksumChunkReferences_Builder*) builderWithPrototype:(FileChecksumChunkReferences*) prototype;

+ (FileChecksumChunkReferences*) parseFromData:(NSData*) data;
+ (FileChecksumChunkReferences*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumChunkReferences*) parseFromInputStream:(NSInputStream*) input;
+ (FileChecksumChunkReferences*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChecksumChunkReferences*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumChunkReferences*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChecksumChunkReferences*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChecksumChunkReferences_Builder : PBGeneratedMessage_Builder {
@private
  FileChecksumChunkReferences* result;
}

- (FileChecksumChunkReferences*) defaultInstance;

- (FileChecksumChunkReferences_Builder*) clear;
- (FileChecksumChunkReferences_Builder*) clone;

- (FileChecksumChunkReferences*) build;
- (FileChecksumChunkReferences*) buildPartial;

- (FileChecksumChunkReferences_Builder*) mergeFrom:(FileChecksumChunkReferences*) other;
- (FileChecksumChunkReferences_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChecksumChunkReferences_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileChecksum;
- (NSData*) fileChecksum;
- (FileChecksumChunkReferences_Builder*) setFileChecksum:(NSData*) value;
- (FileChecksumChunkReferences_Builder*) clearFileChecksum;

- (NSArray*) chunkReferencesList;
- (ChunkReference*) chunkReferencesAtIndex:(int32_t) index;
- (FileChecksumChunkReferences_Builder*) replaceChunkReferencesAtIndex:(int32_t) index with:(ChunkReference*) value;
- (FileChecksumChunkReferences_Builder*) addChunkReferences:(ChunkReference*) value;
- (FileChecksumChunkReferences_Builder*) addAllChunkReferences:(NSArray*) values;
- (FileChecksumChunkReferences_Builder*) clearChunkReferencesList;

- (BOOL) hasFileSignature;
- (NSData*) fileSignature;
- (FileChecksumChunkReferences_Builder*) setFileSignature:(NSData*) value;
- (FileChecksumChunkReferences_Builder*) clearFileSignature;
@end

@interface FileChecksumStorageHostChunkLists : PBGeneratedMessage {
@private
  NSMutableArray* mutableStorageHostChunkListList;
  NSMutableArray* mutableFileChecksumChunkReferencesList;
}
- (NSArray*) storageHostChunkListList;
- (StorageHostChunkList*) storageHostChunkListAtIndex:(int32_t) index;
- (NSArray*) fileChecksumChunkReferencesList;
- (FileChecksumChunkReferences*) fileChecksumChunkReferencesAtIndex:(int32_t) index;

+ (FileChecksumStorageHostChunkLists*) defaultInstance;
- (FileChecksumStorageHostChunkLists*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileChecksumStorageHostChunkLists_Builder*) builder;
+ (FileChecksumStorageHostChunkLists_Builder*) builder;
+ (FileChecksumStorageHostChunkLists_Builder*) builderWithPrototype:(FileChecksumStorageHostChunkLists*) prototype;

+ (FileChecksumStorageHostChunkLists*) parseFromData:(NSData*) data;
+ (FileChecksumStorageHostChunkLists*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumStorageHostChunkLists*) parseFromInputStream:(NSInputStream*) input;
+ (FileChecksumStorageHostChunkLists*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileChecksumStorageHostChunkLists*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileChecksumStorageHostChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileChecksumStorageHostChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileChecksumStorageHostChunkLists_Builder : PBGeneratedMessage_Builder {
@private
  FileChecksumStorageHostChunkLists* result;
}

- (FileChecksumStorageHostChunkLists*) defaultInstance;

- (FileChecksumStorageHostChunkLists_Builder*) clear;
- (FileChecksumStorageHostChunkLists_Builder*) clone;

- (FileChecksumStorageHostChunkLists*) build;
- (FileChecksumStorageHostChunkLists*) buildPartial;

- (FileChecksumStorageHostChunkLists_Builder*) mergeFrom:(FileChecksumStorageHostChunkLists*) other;
- (FileChecksumStorageHostChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileChecksumStorageHostChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) storageHostChunkListList;
- (StorageHostChunkList*) storageHostChunkListAtIndex:(int32_t) index;
- (FileChecksumStorageHostChunkLists_Builder*) replaceStorageHostChunkListAtIndex:(int32_t) index with:(StorageHostChunkList*) value;
- (FileChecksumStorageHostChunkLists_Builder*) addStorageHostChunkList:(StorageHostChunkList*) value;
- (FileChecksumStorageHostChunkLists_Builder*) addAllStorageHostChunkList:(NSArray*) values;
- (FileChecksumStorageHostChunkLists_Builder*) clearStorageHostChunkListList;

- (NSArray*) fileChecksumChunkReferencesList;
- (FileChecksumChunkReferences*) fileChecksumChunkReferencesAtIndex:(int32_t) index;
- (FileChecksumStorageHostChunkLists_Builder*) replaceFileChecksumChunkReferencesAtIndex:(int32_t) index with:(FileChecksumChunkReferences*) value;
- (FileChecksumStorageHostChunkLists_Builder*) addFileChecksumChunkReferences:(FileChecksumChunkReferences*) value;
- (FileChecksumStorageHostChunkLists_Builder*) addAllFileChecksumChunkReferences:(NSArray*) values;
- (FileChecksumStorageHostChunkLists_Builder*) clearFileChecksumChunkReferencesList;
@end

@interface FileGroups : PBGeneratedMessage {
@private
  BOOL hasVerbosityLevel_:1;
  int32_t verbosityLevel;
  NSMutableArray* mutableFileGroupsList;
  NSMutableArray* mutableFileErrorList;
  NSMutableArray* mutableFileChunkErrorList;
}
- (BOOL) hasVerbosityLevel;
@property (readonly) int32_t verbosityLevel;
- (NSArray*) fileGroupsList;
- (FileChecksumStorageHostChunkLists*) fileGroupsAtIndex:(int32_t) index;
- (NSArray*) fileErrorList;
- (FileError*) fileErrorAtIndex:(int32_t) index;
- (NSArray*) fileChunkErrorList;
- (FileChunkError*) fileChunkErrorAtIndex:(int32_t) index;

+ (FileGroups*) defaultInstance;
- (FileGroups*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileGroups_Builder*) builder;
+ (FileGroups_Builder*) builder;
+ (FileGroups_Builder*) builderWithPrototype:(FileGroups*) prototype;

+ (FileGroups*) parseFromData:(NSData*) data;
+ (FileGroups*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileGroups*) parseFromInputStream:(NSInputStream*) input;
+ (FileGroups*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (FileGroups*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileGroups*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileGroups*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileGroups_Builder : PBGeneratedMessage_Builder {
@private
  FileGroups* result;
}

- (FileGroups*) defaultInstance;

- (FileGroups_Builder*) clear;
- (FileGroups_Builder*) clone;

- (FileGroups*) build;
- (FileGroups*) buildPartial;

- (FileGroups_Builder*) mergeFrom:(FileGroups*) other;
- (FileGroups_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileGroups_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) fileGroupsList;
- (FileChecksumStorageHostChunkLists*) fileGroupsAtIndex:(int32_t) index;
- (FileGroups_Builder*) replaceFileGroupsAtIndex:(int32_t) index with:(FileChecksumStorageHostChunkLists*) value;
- (FileGroups_Builder*) addFileGroups:(FileChecksumStorageHostChunkLists*) value;
- (FileGroups_Builder*) addAllFileGroups:(NSArray*) values;
- (FileGroups_Builder*) clearFileGroupsList;

- (NSArray*) fileErrorList;
- (FileError*) fileErrorAtIndex:(int32_t) index;
- (FileGroups_Builder*) replaceFileErrorAtIndex:(int32_t) index with:(FileError*) value;
- (FileGroups_Builder*) addFileError:(FileError*) value;
- (FileGroups_Builder*) addAllFileError:(NSArray*) values;
- (FileGroups_Builder*) clearFileErrorList;

- (NSArray*) fileChunkErrorList;
- (FileChunkError*) fileChunkErrorAtIndex:(int32_t) index;
- (FileGroups_Builder*) replaceFileChunkErrorAtIndex:(int32_t) index with:(FileChunkError*) value;
- (FileGroups_Builder*) addFileChunkError:(FileChunkError*) value;
- (FileGroups_Builder*) addAllFileChunkError:(NSArray*) values;
- (FileGroups_Builder*) clearFileChunkErrorList;

- (BOOL) hasVerbosityLevel;
- (int32_t) verbosityLevel;
- (FileGroups_Builder*) setVerbosityLevel:(int32_t) value;
- (FileGroups_Builder*) clearVerbosityLevel;
@end

@interface ChunkChecksumList : PBGeneratedMessage {
@private
  NSMutableArray* mutableChunkChecksumList;
}
- (NSArray*) chunkChecksumList;
- (NSData*) chunkChecksumAtIndex:(int32_t) index;

+ (ChunkChecksumList*) defaultInstance;
- (ChunkChecksumList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChunkChecksumList_Builder*) builder;
+ (ChunkChecksumList_Builder*) builder;
+ (ChunkChecksumList_Builder*) builderWithPrototype:(ChunkChecksumList*) prototype;

+ (ChunkChecksumList*) parseFromData:(NSData*) data;
+ (ChunkChecksumList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkChecksumList*) parseFromInputStream:(NSInputStream*) input;
+ (ChunkChecksumList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ChunkChecksumList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChunkChecksumList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChunkChecksumList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChunkChecksumList_Builder : PBGeneratedMessage_Builder {
@private
  ChunkChecksumList* result;
}

- (ChunkChecksumList*) defaultInstance;

- (ChunkChecksumList_Builder*) clear;
- (ChunkChecksumList_Builder*) clone;

- (ChunkChecksumList*) build;
- (ChunkChecksumList*) buildPartial;

- (ChunkChecksumList_Builder*) mergeFrom:(ChunkChecksumList*) other;
- (ChunkChecksumList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChunkChecksumList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) chunkChecksumList;
- (NSData*) chunkChecksumAtIndex:(int32_t) index;
- (ChunkChecksumList_Builder*) replaceChunkChecksumAtIndex:(int32_t) index with:(NSData*) value;
- (ChunkChecksumList_Builder*) addChunkChecksum:(NSData*) value;
- (ChunkChecksumList_Builder*) addAllChunkChecksum:(NSArray*) values;
- (ChunkChecksumList_Builder*) clearChunkChecksumList;
@end

@interface StorageHostChunkList : PBGeneratedMessage {
@private
  BOOL hasStorageContainerKey_:1;
  BOOL hasStorageContainerAuthorizationToken_:1;
  BOOL hasHostInfo_:1;
  NSString* storageContainerKey;
  NSString* storageContainerAuthorizationToken;
  HostInfo* hostInfo;
  NSMutableArray* mutableChunkInfoList;
}
- (BOOL) hasHostInfo;
- (BOOL) hasStorageContainerKey;
- (BOOL) hasStorageContainerAuthorizationToken;
@property (readonly, retain) HostInfo* hostInfo;
@property (readonly, retain) NSString* storageContainerKey;
@property (readonly, retain) NSString* storageContainerAuthorizationToken;
- (NSArray*) chunkInfoList;
- (ChunkInfo*) chunkInfoAtIndex:(int32_t) index;

+ (StorageHostChunkList*) defaultInstance;
- (StorageHostChunkList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageHostChunkList_Builder*) builder;
+ (StorageHostChunkList_Builder*) builder;
+ (StorageHostChunkList_Builder*) builderWithPrototype:(StorageHostChunkList*) prototype;

+ (StorageHostChunkList*) parseFromData:(NSData*) data;
+ (StorageHostChunkList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageHostChunkList*) parseFromInputStream:(NSInputStream*) input;
+ (StorageHostChunkList*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageHostChunkList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageHostChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageHostChunkList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageHostChunkList_Builder : PBGeneratedMessage_Builder {
@private
  StorageHostChunkList* result;
}

- (StorageHostChunkList*) defaultInstance;

- (StorageHostChunkList_Builder*) clear;
- (StorageHostChunkList_Builder*) clone;

- (StorageHostChunkList*) build;
- (StorageHostChunkList*) buildPartial;

- (StorageHostChunkList_Builder*) mergeFrom:(StorageHostChunkList*) other;
- (StorageHostChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageHostChunkList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHostInfo;
- (HostInfo*) hostInfo;
- (StorageHostChunkList_Builder*) setHostInfo:(HostInfo*) value;
- (StorageHostChunkList_Builder*) setHostInfoBuilder:(HostInfo_Builder*) builderForValue;
- (StorageHostChunkList_Builder*) mergeHostInfo:(HostInfo*) value;
- (StorageHostChunkList_Builder*) clearHostInfo;

- (NSArray*) chunkInfoList;
- (ChunkInfo*) chunkInfoAtIndex:(int32_t) index;
- (StorageHostChunkList_Builder*) replaceChunkInfoAtIndex:(int32_t) index with:(ChunkInfo*) value;
- (StorageHostChunkList_Builder*) addChunkInfo:(ChunkInfo*) value;
- (StorageHostChunkList_Builder*) addAllChunkInfo:(NSArray*) values;
- (StorageHostChunkList_Builder*) clearChunkInfoList;

- (BOOL) hasStorageContainerKey;
- (NSString*) storageContainerKey;
- (StorageHostChunkList_Builder*) setStorageContainerKey:(NSString*) value;
- (StorageHostChunkList_Builder*) clearStorageContainerKey;

- (BOOL) hasStorageContainerAuthorizationToken;
- (NSString*) storageContainerAuthorizationToken;
- (StorageHostChunkList_Builder*) setStorageContainerAuthorizationToken:(NSString*) value;
- (StorageHostChunkList_Builder*) clearStorageContainerAuthorizationToken;
@end

@interface StorageHostChunkLists : PBGeneratedMessage {
@private
  NSMutableArray* mutableStorageHostChunkListList;
  NSMutableArray* mutableChunkErrorList;
}
- (NSArray*) storageHostChunkListList;
- (StorageHostChunkList*) storageHostChunkListAtIndex:(int32_t) index;
- (NSArray*) chunkErrorList;
- (ChunkError*) chunkErrorAtIndex:(int32_t) index;

+ (StorageHostChunkLists*) defaultInstance;
- (StorageHostChunkLists*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StorageHostChunkLists_Builder*) builder;
+ (StorageHostChunkLists_Builder*) builder;
+ (StorageHostChunkLists_Builder*) builderWithPrototype:(StorageHostChunkLists*) prototype;

+ (StorageHostChunkLists*) parseFromData:(NSData*) data;
+ (StorageHostChunkLists*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageHostChunkLists*) parseFromInputStream:(NSInputStream*) input;
+ (StorageHostChunkLists*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (StorageHostChunkLists*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StorageHostChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StorageHostChunkLists*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StorageHostChunkLists_Builder : PBGeneratedMessage_Builder {
@private
  StorageHostChunkLists* result;
}

- (StorageHostChunkLists*) defaultInstance;

- (StorageHostChunkLists_Builder*) clear;
- (StorageHostChunkLists_Builder*) clone;

- (StorageHostChunkLists*) build;
- (StorageHostChunkLists*) buildPartial;

- (StorageHostChunkLists_Builder*) mergeFrom:(StorageHostChunkLists*) other;
- (StorageHostChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StorageHostChunkLists_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) storageHostChunkListList;
- (StorageHostChunkList*) storageHostChunkListAtIndex:(int32_t) index;
- (StorageHostChunkLists_Builder*) replaceStorageHostChunkListAtIndex:(int32_t) index with:(StorageHostChunkList*) value;
- (StorageHostChunkLists_Builder*) addStorageHostChunkList:(StorageHostChunkList*) value;
- (StorageHostChunkLists_Builder*) addAllStorageHostChunkList:(NSArray*) values;
- (StorageHostChunkLists_Builder*) clearStorageHostChunkListList;

- (NSArray*) chunkErrorList;
- (ChunkError*) chunkErrorAtIndex:(int32_t) index;
- (StorageHostChunkLists_Builder*) replaceChunkErrorAtIndex:(int32_t) index with:(ChunkError*) value;
- (StorageHostChunkLists_Builder*) addChunkError:(ChunkError*) value;
- (StorageHostChunkLists_Builder*) addAllChunkError:(NSArray*) values;
- (StorageHostChunkLists_Builder*) clearChunkErrorList;
@end

