// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Protocolbuffers.h"

@class MBSAccount;
@class MBSAccount_Builder;
@class MBSBackup;
@class MBSBackupAttributes;
@class MBSBackupAttributes_Builder;
@class MBSBackup_Builder;
@class MBSFile;
@class MBSFileAttributes;
@class MBSFileAttributes_Builder;
@class MBSFileAuthToken;
@class MBSFileAuthToken_Builder;
@class MBSFileAuthTokens;
@class MBSFileAuthTokens_Builder;
@class MBSFileExtendedAttribute;
@class MBSFileExtendedAttribute_Builder;
@class MBSFileID;
@class MBSFileID_Builder;
@class MBSFile_Builder;
@class MBSKey;
@class MBSKeySet;
@class MBSKeySet_Builder;
@class MBSKey_Builder;
@class MBSSnapshot;
@class MBSSnapshotAttributes;
@class MBSSnapshotAttributes_Builder;
@class MBSSnapshotID;
@class MBSSnapshotID_Builder;
@class MBSSnapshot_Builder;

@interface IcloudRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MBSAccount : PBGeneratedMessage {
@private
  BOOL hasAccountId_:1;
  NSString* accountId;
  NSMutableArray* mutableBackupUdidList;
}
- (BOOL) hasAccountId;
@property (readonly, retain) NSString* accountId;
- (NSArray*) backupUdidList;
- (NSData*) backupUdidAtIndex:(int32_t) index;

+ (MBSAccount*) defaultInstance;
- (MBSAccount*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSAccount_Builder*) builder;
+ (MBSAccount_Builder*) builder;
+ (MBSAccount_Builder*) builderWithPrototype:(MBSAccount*) prototype;

+ (MBSAccount*) parseFromData:(NSData*) data;
+ (MBSAccount*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSAccount*) parseFromInputStream:(NSInputStream*) input;
+ (MBSAccount*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSAccount*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSAccount*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSAccount*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSAccount_Builder : PBGeneratedMessage_Builder {
@private
  MBSAccount* result;
}

- (MBSAccount*) defaultInstance;

- (MBSAccount_Builder*) clear;
- (MBSAccount_Builder*) clone;

- (MBSAccount*) build;
- (MBSAccount*) buildPartial;

- (MBSAccount_Builder*) mergeFrom:(MBSAccount*) other;
- (MBSAccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSAccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAccountId;
- (NSString*) accountId;
- (MBSAccount_Builder*) setAccountId:(NSString*) value;
- (MBSAccount_Builder*) clearAccountId;

- (NSArray*) backupUdidList;
- (NSData*) backupUdidAtIndex:(int32_t) index;
- (MBSAccount_Builder*) replaceBackupUdidAtIndex:(int32_t) index with:(NSData*) value;
- (MBSAccount_Builder*) addBackupUdid:(NSData*) value;
- (MBSAccount_Builder*) addAllBackupUdid:(NSArray*) values;
- (MBSAccount_Builder*) clearBackupUdidList;
@end

@interface MBSBackup : PBGeneratedMessage {
@private
  BOOL hasQuotaUsed_:1;
  BOOL hasKeysLastModified_:1;
  BOOL hasAttributes_:1;
  BOOL hasBackupUdid_:1;
  int64_t quotaUsed;
  int64_t keysLastModified;
  MBSBackupAttributes* attributes;
  NSData* backupUdid;
  NSMutableArray* mutableSnapshotList;
}
- (BOOL) hasBackupUdid;
- (BOOL) hasQuotaUsed;
- (BOOL) hasAttributes;
- (BOOL) hasKeysLastModified;
@property (readonly, retain) NSData* backupUdid;
@property (readonly) int64_t quotaUsed;
@property (readonly, retain) MBSBackupAttributes* attributes;
@property (readonly) int64_t keysLastModified;
- (NSArray*) snapshotList;
- (MBSSnapshot*) snapshotAtIndex:(int32_t) index;

+ (MBSBackup*) defaultInstance;
- (MBSBackup*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSBackup_Builder*) builder;
+ (MBSBackup_Builder*) builder;
+ (MBSBackup_Builder*) builderWithPrototype:(MBSBackup*) prototype;

+ (MBSBackup*) parseFromData:(NSData*) data;
+ (MBSBackup*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSBackup*) parseFromInputStream:(NSInputStream*) input;
+ (MBSBackup*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSBackup*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSBackup*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSBackup*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSBackup_Builder : PBGeneratedMessage_Builder {
@private
  MBSBackup* result;
}

- (MBSBackup*) defaultInstance;

- (MBSBackup_Builder*) clear;
- (MBSBackup_Builder*) clone;

- (MBSBackup*) build;
- (MBSBackup*) buildPartial;

- (MBSBackup_Builder*) mergeFrom:(MBSBackup*) other;
- (MBSBackup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSBackup_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBackupUdid;
- (NSData*) backupUdid;
- (MBSBackup_Builder*) setBackupUdid:(NSData*) value;
- (MBSBackup_Builder*) clearBackupUdid;

- (BOOL) hasQuotaUsed;
- (int64_t) quotaUsed;
- (MBSBackup_Builder*) setQuotaUsed:(int64_t) value;
- (MBSBackup_Builder*) clearQuotaUsed;

- (NSArray*) snapshotList;
- (MBSSnapshot*) snapshotAtIndex:(int32_t) index;
- (MBSBackup_Builder*) replaceSnapshotAtIndex:(int32_t) index with:(MBSSnapshot*) value;
- (MBSBackup_Builder*) addSnapshot:(MBSSnapshot*) value;
- (MBSBackup_Builder*) addAllSnapshot:(NSArray*) values;
- (MBSBackup_Builder*) clearSnapshotList;

- (BOOL) hasAttributes;
- (MBSBackupAttributes*) attributes;
- (MBSBackup_Builder*) setAttributes:(MBSBackupAttributes*) value;
- (MBSBackup_Builder*) setAttributesBuilder:(MBSBackupAttributes_Builder*) builderForValue;
- (MBSBackup_Builder*) mergeAttributes:(MBSBackupAttributes*) value;
- (MBSBackup_Builder*) clearAttributes;

- (BOOL) hasKeysLastModified;
- (int64_t) keysLastModified;
- (MBSBackup_Builder*) setKeysLastModified:(int64_t) value;
- (MBSBackup_Builder*) clearKeysLastModified;
@end

@interface MBSBackupAttributes : PBGeneratedMessage {
@private
  BOOL hasDeviceClass_:1;
  BOOL hasProductType_:1;
  BOOL hasSerialNumber_:1;
  BOOL hasDeviceColor_:1;
  BOOL hasHardwareModel_:1;
  BOOL hasMarketingName_:1;
  NSString* deviceClass;
  NSString* productType;
  NSString* serialNumber;
  NSString* deviceColor;
  NSString* hardwareModel;
  NSString* marketingName;
}
- (BOOL) hasDeviceClass;
- (BOOL) hasProductType;
- (BOOL) hasSerialNumber;
- (BOOL) hasDeviceColor;
- (BOOL) hasHardwareModel;
- (BOOL) hasMarketingName;
@property (readonly, retain) NSString* deviceClass;
@property (readonly, retain) NSString* productType;
@property (readonly, retain) NSString* serialNumber;
@property (readonly, retain) NSString* deviceColor;
@property (readonly, retain) NSString* hardwareModel;
@property (readonly, retain) NSString* marketingName;

+ (MBSBackupAttributes*) defaultInstance;
- (MBSBackupAttributes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSBackupAttributes_Builder*) builder;
+ (MBSBackupAttributes_Builder*) builder;
+ (MBSBackupAttributes_Builder*) builderWithPrototype:(MBSBackupAttributes*) prototype;

+ (MBSBackupAttributes*) parseFromData:(NSData*) data;
+ (MBSBackupAttributes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSBackupAttributes*) parseFromInputStream:(NSInputStream*) input;
+ (MBSBackupAttributes*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSBackupAttributes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSBackupAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSBackupAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSBackupAttributes_Builder : PBGeneratedMessage_Builder {
@private
  MBSBackupAttributes* result;
}

- (MBSBackupAttributes*) defaultInstance;

- (MBSBackupAttributes_Builder*) clear;
- (MBSBackupAttributes_Builder*) clone;

- (MBSBackupAttributes*) build;
- (MBSBackupAttributes*) buildPartial;

- (MBSBackupAttributes_Builder*) mergeFrom:(MBSBackupAttributes*) other;
- (MBSBackupAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSBackupAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceClass;
- (NSString*) deviceClass;
- (MBSBackupAttributes_Builder*) setDeviceClass:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearDeviceClass;

- (BOOL) hasProductType;
- (NSString*) productType;
- (MBSBackupAttributes_Builder*) setProductType:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearProductType;

- (BOOL) hasSerialNumber;
- (NSString*) serialNumber;
- (MBSBackupAttributes_Builder*) setSerialNumber:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearSerialNumber;

- (BOOL) hasDeviceColor;
- (NSString*) deviceColor;
- (MBSBackupAttributes_Builder*) setDeviceColor:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearDeviceColor;

- (BOOL) hasHardwareModel;
- (NSString*) hardwareModel;
- (MBSBackupAttributes_Builder*) setHardwareModel:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearHardwareModel;

- (BOOL) hasMarketingName;
- (NSString*) marketingName;
- (MBSBackupAttributes_Builder*) setMarketingName:(NSString*) value;
- (MBSBackupAttributes_Builder*) clearMarketingName;
@end

@interface MBSFile : PBGeneratedMessage {
@private
  BOOL hasSize_:1;
  BOOL hasDomain_:1;
  BOOL hasRelativePath_:1;
  BOOL hasAttributes_:1;
  BOOL hasFileId_:1;
  BOOL hasSignature_:1;
  int64_t size;
  NSString* domain;
  NSString* relativePath;
  MBSFileAttributes* attributes;
  NSData* fileId;
  NSData* signature;
}
- (BOOL) hasFileId;
- (BOOL) hasDomain;
- (BOOL) hasRelativePath;
- (BOOL) hasSignature;
- (BOOL) hasSize;
- (BOOL) hasAttributes;
@property (readonly, retain) NSData* fileId;
@property (readonly, retain) NSString* domain;
@property (readonly, retain) NSString* relativePath;
@property (readonly, retain) NSData* signature;
@property (readonly) int64_t size;
@property (readonly, retain) MBSFileAttributes* attributes;

+ (MBSFile*) defaultInstance;
- (MBSFile*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFile_Builder*) builder;
+ (MBSFile_Builder*) builder;
+ (MBSFile_Builder*) builderWithPrototype:(MBSFile*) prototype;

+ (MBSFile*) parseFromData:(NSData*) data;
+ (MBSFile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFile*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFile*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFile_Builder : PBGeneratedMessage_Builder {
@private
  MBSFile* result;
}

- (MBSFile*) defaultInstance;

- (MBSFile_Builder*) clear;
- (MBSFile_Builder*) clone;

- (MBSFile*) build;
- (MBSFile*) buildPartial;

- (MBSFile_Builder*) mergeFrom:(MBSFile*) other;
- (MBSFile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFile_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileId;
- (NSData*) fileId;
- (MBSFile_Builder*) setFileId:(NSData*) value;
- (MBSFile_Builder*) clearFileId;

- (BOOL) hasDomain;
- (NSString*) domain;
- (MBSFile_Builder*) setDomain:(NSString*) value;
- (MBSFile_Builder*) clearDomain;

- (BOOL) hasRelativePath;
- (NSString*) relativePath;
- (MBSFile_Builder*) setRelativePath:(NSString*) value;
- (MBSFile_Builder*) clearRelativePath;

- (BOOL) hasSignature;
- (NSData*) signature;
- (MBSFile_Builder*) setSignature:(NSData*) value;
- (MBSFile_Builder*) clearSignature;

- (BOOL) hasSize;
- (int64_t) size;
- (MBSFile_Builder*) setSize:(int64_t) value;
- (MBSFile_Builder*) clearSize;

- (BOOL) hasAttributes;
- (MBSFileAttributes*) attributes;
- (MBSFile_Builder*) setAttributes:(MBSFileAttributes*) value;
- (MBSFile_Builder*) setAttributesBuilder:(MBSFileAttributes_Builder*) builderForValue;
- (MBSFile_Builder*) mergeAttributes:(MBSFileAttributes*) value;
- (MBSFile_Builder*) clearAttributes;
@end

@interface MBSFileAttributes : PBGeneratedMessage {
@private
  BOOL hasInodeNumber_:1;
  BOOL hasLastModified_:1;
  BOOL hasLastStatusChange_:1;
  BOOL hasBirth_:1;
  BOOL hasDecryptedSize_:1;
  BOOL hasTarget_:1;
  BOOL hasExtendedAttribute_:1;
  BOOL hasEncryptionKey_:1;
  BOOL hasKeybagId_:1;
  BOOL hasMode_:1;
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasProtectionClass_:1;
  BOOL hasEncryptionKeyVersion_:1;
  int64_t inodeNumber;
  int64_t lastModified;
  int64_t lastStatusChange;
  int64_t birth;
  int64_t decryptedSize;
  NSString* target;
  MBSFileExtendedAttribute* extendedAttribute;
  NSData* encryptionKey;
  int32_t keybagId;
  int32_t mode;
  int32_t userId;
  int32_t groupId;
  int32_t protectionClass;
  int32_t encryptionKeyVersion;
}
- (BOOL) hasKeybagId;
- (BOOL) hasTarget;
- (BOOL) hasEncryptionKey;
- (BOOL) hasInodeNumber;
- (BOOL) hasMode;
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasLastModified;
- (BOOL) hasLastStatusChange;
- (BOOL) hasBirth;
- (BOOL) hasProtectionClass;
- (BOOL) hasExtendedAttribute;
- (BOOL) hasEncryptionKeyVersion;
- (BOOL) hasDecryptedSize;
@property (readonly) int32_t keybagId;
@property (readonly, retain) NSString* target;
@property (readonly, retain) NSData* encryptionKey;
@property (readonly) int64_t inodeNumber;
@property (readonly) int32_t mode;
@property (readonly) int32_t userId;
@property (readonly) int32_t groupId;
@property (readonly) int64_t lastModified;
@property (readonly) int64_t lastStatusChange;
@property (readonly) int64_t birth;
@property (readonly) int32_t protectionClass;
@property (readonly, retain) MBSFileExtendedAttribute* extendedAttribute;
@property (readonly) int32_t encryptionKeyVersion;
@property (readonly) int64_t decryptedSize;

+ (MBSFileAttributes*) defaultInstance;
- (MBSFileAttributes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFileAttributes_Builder*) builder;
+ (MBSFileAttributes_Builder*) builder;
+ (MBSFileAttributes_Builder*) builderWithPrototype:(MBSFileAttributes*) prototype;

+ (MBSFileAttributes*) parseFromData:(NSData*) data;
+ (MBSFileAttributes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAttributes*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFileAttributes*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFileAttributes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFileAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFileAttributes_Builder : PBGeneratedMessage_Builder {
@private
  MBSFileAttributes* result;
}

- (MBSFileAttributes*) defaultInstance;

- (MBSFileAttributes_Builder*) clear;
- (MBSFileAttributes_Builder*) clone;

- (MBSFileAttributes*) build;
- (MBSFileAttributes*) buildPartial;

- (MBSFileAttributes_Builder*) mergeFrom:(MBSFileAttributes*) other;
- (MBSFileAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFileAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKeybagId;
- (int32_t) keybagId;
- (MBSFileAttributes_Builder*) setKeybagId:(int32_t) value;
- (MBSFileAttributes_Builder*) clearKeybagId;

- (BOOL) hasTarget;
- (NSString*) target;
- (MBSFileAttributes_Builder*) setTarget:(NSString*) value;
- (MBSFileAttributes_Builder*) clearTarget;

- (BOOL) hasEncryptionKey;
- (NSData*) encryptionKey;
- (MBSFileAttributes_Builder*) setEncryptionKey:(NSData*) value;
- (MBSFileAttributes_Builder*) clearEncryptionKey;

- (BOOL) hasInodeNumber;
- (int64_t) inodeNumber;
- (MBSFileAttributes_Builder*) setInodeNumber:(int64_t) value;
- (MBSFileAttributes_Builder*) clearInodeNumber;

- (BOOL) hasMode;
- (int32_t) mode;
- (MBSFileAttributes_Builder*) setMode:(int32_t) value;
- (MBSFileAttributes_Builder*) clearMode;

- (BOOL) hasUserId;
- (int32_t) userId;
- (MBSFileAttributes_Builder*) setUserId:(int32_t) value;
- (MBSFileAttributes_Builder*) clearUserId;

- (BOOL) hasGroupId;
- (int32_t) groupId;
- (MBSFileAttributes_Builder*) setGroupId:(int32_t) value;
- (MBSFileAttributes_Builder*) clearGroupId;

- (BOOL) hasLastModified;
- (int64_t) lastModified;
- (MBSFileAttributes_Builder*) setLastModified:(int64_t) value;
- (MBSFileAttributes_Builder*) clearLastModified;

- (BOOL) hasLastStatusChange;
- (int64_t) lastStatusChange;
- (MBSFileAttributes_Builder*) setLastStatusChange:(int64_t) value;
- (MBSFileAttributes_Builder*) clearLastStatusChange;

- (BOOL) hasBirth;
- (int64_t) birth;
- (MBSFileAttributes_Builder*) setBirth:(int64_t) value;
- (MBSFileAttributes_Builder*) clearBirth;

- (BOOL) hasProtectionClass;
- (int32_t) protectionClass;
- (MBSFileAttributes_Builder*) setProtectionClass:(int32_t) value;
- (MBSFileAttributes_Builder*) clearProtectionClass;

- (BOOL) hasExtendedAttribute;
- (MBSFileExtendedAttribute*) extendedAttribute;
- (MBSFileAttributes_Builder*) setExtendedAttribute:(MBSFileExtendedAttribute*) value;
- (MBSFileAttributes_Builder*) setExtendedAttributeBuilder:(MBSFileExtendedAttribute_Builder*) builderForValue;
- (MBSFileAttributes_Builder*) mergeExtendedAttribute:(MBSFileExtendedAttribute*) value;
- (MBSFileAttributes_Builder*) clearExtendedAttribute;

- (BOOL) hasEncryptionKeyVersion;
- (int32_t) encryptionKeyVersion;
- (MBSFileAttributes_Builder*) setEncryptionKeyVersion:(int32_t) value;
- (MBSFileAttributes_Builder*) clearEncryptionKeyVersion;

- (BOOL) hasDecryptedSize;
- (int64_t) decryptedSize;
- (MBSFileAttributes_Builder*) setDecryptedSize:(int64_t) value;
- (MBSFileAttributes_Builder*) clearDecryptedSize;
@end

@interface MBSSnapshot : PBGeneratedMessage {
@private
  BOOL hasQuotaReserved_:1;
  BOOL hasLastModified_:1;
  BOOL hasCommitted_:1;
  BOOL hasAttributes_:1;
  BOOL hasSnapshotId_:1;
  int64_t quotaReserved;
  int64_t lastModified;
  int64_t committed;
  MBSSnapshotAttributes* attributes;
  int32_t snapshotId;
}
- (BOOL) hasSnapshotId;
- (BOOL) hasQuotaReserved;
- (BOOL) hasLastModified;
- (BOOL) hasAttributes;
- (BOOL) hasCommitted;
@property (readonly) int32_t snapshotId;
@property (readonly) int64_t quotaReserved;
@property (readonly) int64_t lastModified;
@property (readonly, retain) MBSSnapshotAttributes* attributes;
@property (readonly) int64_t committed;

+ (MBSSnapshot*) defaultInstance;
- (MBSSnapshot*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSSnapshot_Builder*) builder;
+ (MBSSnapshot_Builder*) builder;
+ (MBSSnapshot_Builder*) builderWithPrototype:(MBSSnapshot*) prototype;

+ (MBSSnapshot*) parseFromData:(NSData*) data;
+ (MBSSnapshot*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshot*) parseFromInputStream:(NSInputStream*) input;
+ (MBSSnapshot*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSSnapshot*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshot*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSSnapshot*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSSnapshot_Builder : PBGeneratedMessage_Builder {
@private
  MBSSnapshot* result;
}

- (MBSSnapshot*) defaultInstance;

- (MBSSnapshot_Builder*) clear;
- (MBSSnapshot_Builder*) clone;

- (MBSSnapshot*) build;
- (MBSSnapshot*) buildPartial;

- (MBSSnapshot_Builder*) mergeFrom:(MBSSnapshot*) other;
- (MBSSnapshot_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSSnapshot_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSnapshotId;
- (int32_t) snapshotId;
- (MBSSnapshot_Builder*) setSnapshotId:(int32_t) value;
- (MBSSnapshot_Builder*) clearSnapshotId;

- (BOOL) hasQuotaReserved;
- (int64_t) quotaReserved;
- (MBSSnapshot_Builder*) setQuotaReserved:(int64_t) value;
- (MBSSnapshot_Builder*) clearQuotaReserved;

- (BOOL) hasLastModified;
- (int64_t) lastModified;
- (MBSSnapshot_Builder*) setLastModified:(int64_t) value;
- (MBSSnapshot_Builder*) clearLastModified;

- (BOOL) hasAttributes;
- (MBSSnapshotAttributes*) attributes;
- (MBSSnapshot_Builder*) setAttributes:(MBSSnapshotAttributes*) value;
- (MBSSnapshot_Builder*) setAttributesBuilder:(MBSSnapshotAttributes_Builder*) builderForValue;
- (MBSSnapshot_Builder*) mergeAttributes:(MBSSnapshotAttributes*) value;
- (MBSSnapshot_Builder*) clearAttributes;

- (BOOL) hasCommitted;
- (int64_t) committed;
- (MBSSnapshot_Builder*) setCommitted:(int64_t) value;
- (MBSSnapshot_Builder*) clearCommitted;
@end

@interface MBSSnapshotAttributes : PBGeneratedMessage {
@private
  BOOL hasBackupReason_:1;
  BOOL hasBackupType_:1;
  BOOL hasDeviceName_:1;
  BOOL hasProductVersion_:1;
  BOOL hasBuildVersion_:1;
  BOOL hasKeybagUuid_:1;
  BOOL hasKeybagId_:1;
  int32_t backupReason;
  int32_t backupType;
  NSString* deviceName;
  NSString* productVersion;
  NSString* buildVersion;
  NSData* keybagUuid;
  int32_t keybagId;
}
- (BOOL) hasDeviceName;
- (BOOL) hasProductVersion;
- (BOOL) hasBuildVersion;
- (BOOL) hasKeybagId;
- (BOOL) hasKeybagUuid;
- (BOOL) hasBackupReason;
- (BOOL) hasBackupType;
@property (readonly, retain) NSString* deviceName;
@property (readonly, retain) NSString* productVersion;
@property (readonly, retain) NSString* buildVersion;
@property (readonly) int32_t keybagId;
@property (readonly, retain) NSData* keybagUuid;
@property (readonly) int32_t backupReason;
@property (readonly) int32_t backupType;

+ (MBSSnapshotAttributes*) defaultInstance;
- (MBSSnapshotAttributes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSSnapshotAttributes_Builder*) builder;
+ (MBSSnapshotAttributes_Builder*) builder;
+ (MBSSnapshotAttributes_Builder*) builderWithPrototype:(MBSSnapshotAttributes*) prototype;

+ (MBSSnapshotAttributes*) parseFromData:(NSData*) data;
+ (MBSSnapshotAttributes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshotAttributes*) parseFromInputStream:(NSInputStream*) input;
+ (MBSSnapshotAttributes*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSSnapshotAttributes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshotAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSSnapshotAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSSnapshotAttributes_Builder : PBGeneratedMessage_Builder {
@private
  MBSSnapshotAttributes* result;
}

- (MBSSnapshotAttributes*) defaultInstance;

- (MBSSnapshotAttributes_Builder*) clear;
- (MBSSnapshotAttributes_Builder*) clone;

- (MBSSnapshotAttributes*) build;
- (MBSSnapshotAttributes*) buildPartial;

- (MBSSnapshotAttributes_Builder*) mergeFrom:(MBSSnapshotAttributes*) other;
- (MBSSnapshotAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSSnapshotAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceName;
- (NSString*) deviceName;
- (MBSSnapshotAttributes_Builder*) setDeviceName:(NSString*) value;
- (MBSSnapshotAttributes_Builder*) clearDeviceName;

- (BOOL) hasProductVersion;
- (NSString*) productVersion;
- (MBSSnapshotAttributes_Builder*) setProductVersion:(NSString*) value;
- (MBSSnapshotAttributes_Builder*) clearProductVersion;

- (BOOL) hasBuildVersion;
- (NSString*) buildVersion;
- (MBSSnapshotAttributes_Builder*) setBuildVersion:(NSString*) value;
- (MBSSnapshotAttributes_Builder*) clearBuildVersion;

- (BOOL) hasKeybagId;
- (int32_t) keybagId;
- (MBSSnapshotAttributes_Builder*) setKeybagId:(int32_t) value;
- (MBSSnapshotAttributes_Builder*) clearKeybagId;

- (BOOL) hasKeybagUuid;
- (NSData*) keybagUuid;
- (MBSSnapshotAttributes_Builder*) setKeybagUuid:(NSData*) value;
- (MBSSnapshotAttributes_Builder*) clearKeybagUuid;

- (BOOL) hasBackupReason;
- (int32_t) backupReason;
- (MBSSnapshotAttributes_Builder*) setBackupReason:(int32_t) value;
- (MBSSnapshotAttributes_Builder*) clearBackupReason;

- (BOOL) hasBackupType;
- (int32_t) backupType;
- (MBSSnapshotAttributes_Builder*) setBackupType:(int32_t) value;
- (MBSSnapshotAttributes_Builder*) clearBackupType;
@end

@interface MBSSnapshotID : PBGeneratedMessage {
@private
  BOOL hasSnapshotId_:1;
  int32_t snapshotId;
}
- (BOOL) hasSnapshotId;
@property (readonly) int32_t snapshotId;

+ (MBSSnapshotID*) defaultInstance;
- (MBSSnapshotID*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSSnapshotID_Builder*) builder;
+ (MBSSnapshotID_Builder*) builder;
+ (MBSSnapshotID_Builder*) builderWithPrototype:(MBSSnapshotID*) prototype;

+ (MBSSnapshotID*) parseFromData:(NSData*) data;
+ (MBSSnapshotID*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshotID*) parseFromInputStream:(NSInputStream*) input;
+ (MBSSnapshotID*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSSnapshotID*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSSnapshotID*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSSnapshotID*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSSnapshotID_Builder : PBGeneratedMessage_Builder {
@private
  MBSSnapshotID* result;
}

- (MBSSnapshotID*) defaultInstance;

- (MBSSnapshotID_Builder*) clear;
- (MBSSnapshotID_Builder*) clone;

- (MBSSnapshotID*) build;
- (MBSSnapshotID*) buildPartial;

- (MBSSnapshotID_Builder*) mergeFrom:(MBSSnapshotID*) other;
- (MBSSnapshotID_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSSnapshotID_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSnapshotId;
- (int32_t) snapshotId;
- (MBSSnapshotID_Builder*) setSnapshotId:(int32_t) value;
- (MBSSnapshotID_Builder*) clearSnapshotId;
@end

@interface MBSFileAuthToken : PBGeneratedMessage {
@private
  BOOL hasAuthToken_:1;
  BOOL hasFileId_:1;
  NSString* authToken;
  NSData* fileId;
}
- (BOOL) hasFileId;
- (BOOL) hasAuthToken;
@property (readonly, retain) NSData* fileId;
@property (readonly, retain) NSString* authToken;

+ (MBSFileAuthToken*) defaultInstance;
- (MBSFileAuthToken*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFileAuthToken_Builder*) builder;
+ (MBSFileAuthToken_Builder*) builder;
+ (MBSFileAuthToken_Builder*) builderWithPrototype:(MBSFileAuthToken*) prototype;

+ (MBSFileAuthToken*) parseFromData:(NSData*) data;
+ (MBSFileAuthToken*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAuthToken*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFileAuthToken*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFileAuthToken*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAuthToken*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFileAuthToken*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFileAuthToken_Builder : PBGeneratedMessage_Builder {
@private
  MBSFileAuthToken* result;
}

- (MBSFileAuthToken*) defaultInstance;

- (MBSFileAuthToken_Builder*) clear;
- (MBSFileAuthToken_Builder*) clone;

- (MBSFileAuthToken*) build;
- (MBSFileAuthToken*) buildPartial;

- (MBSFileAuthToken_Builder*) mergeFrom:(MBSFileAuthToken*) other;
- (MBSFileAuthToken_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFileAuthToken_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileId;
- (NSData*) fileId;
- (MBSFileAuthToken_Builder*) setFileId:(NSData*) value;
- (MBSFileAuthToken_Builder*) clearFileId;

- (BOOL) hasAuthToken;
- (NSString*) authToken;
- (MBSFileAuthToken_Builder*) setAuthToken:(NSString*) value;
- (MBSFileAuthToken_Builder*) clearAuthToken;
@end

@interface MBSFileAuthTokens : PBGeneratedMessage {
@private
  NSMutableArray* mutableTokensList;
}
- (NSArray*) tokensList;
- (MBSFileAuthToken*) tokensAtIndex:(int32_t) index;

+ (MBSFileAuthTokens*) defaultInstance;
- (MBSFileAuthTokens*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFileAuthTokens_Builder*) builder;
+ (MBSFileAuthTokens_Builder*) builder;
+ (MBSFileAuthTokens_Builder*) builderWithPrototype:(MBSFileAuthTokens*) prototype;

+ (MBSFileAuthTokens*) parseFromData:(NSData*) data;
+ (MBSFileAuthTokens*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAuthTokens*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFileAuthTokens*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFileAuthTokens*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileAuthTokens*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFileAuthTokens*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFileAuthTokens_Builder : PBGeneratedMessage_Builder {
@private
  MBSFileAuthTokens* result;
}

- (MBSFileAuthTokens*) defaultInstance;

- (MBSFileAuthTokens_Builder*) clear;
- (MBSFileAuthTokens_Builder*) clone;

- (MBSFileAuthTokens*) build;
- (MBSFileAuthTokens*) buildPartial;

- (MBSFileAuthTokens_Builder*) mergeFrom:(MBSFileAuthTokens*) other;
- (MBSFileAuthTokens_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFileAuthTokens_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) tokensList;
- (MBSFileAuthToken*) tokensAtIndex:(int32_t) index;
- (MBSFileAuthTokens_Builder*) replaceTokensAtIndex:(int32_t) index with:(MBSFileAuthToken*) value;
- (MBSFileAuthTokens_Builder*) addTokens:(MBSFileAuthToken*) value;
- (MBSFileAuthTokens_Builder*) addAllTokens:(NSArray*) values;
- (MBSFileAuthTokens_Builder*) clearTokensList;
@end

@interface MBSFileID : PBGeneratedMessage {
@private
  BOOL hasFileId_:1;
  NSData* fileId;
}
- (BOOL) hasFileId;
@property (readonly, retain) NSData* fileId;

+ (MBSFileID*) defaultInstance;
- (MBSFileID*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFileID_Builder*) builder;
+ (MBSFileID_Builder*) builder;
+ (MBSFileID_Builder*) builderWithPrototype:(MBSFileID*) prototype;

+ (MBSFileID*) parseFromData:(NSData*) data;
+ (MBSFileID*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileID*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFileID*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFileID*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileID*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFileID*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFileID_Builder : PBGeneratedMessage_Builder {
@private
  MBSFileID* result;
}

- (MBSFileID*) defaultInstance;

- (MBSFileID_Builder*) clear;
- (MBSFileID_Builder*) clone;

- (MBSFileID*) build;
- (MBSFileID*) buildPartial;

- (MBSFileID_Builder*) mergeFrom:(MBSFileID*) other;
- (MBSFileID_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFileID_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFileId;
- (NSData*) fileId;
- (MBSFileID_Builder*) setFileId:(NSData*) value;
- (MBSFileID_Builder*) clearFileId;
@end

@interface MBSKey : PBGeneratedMessage {
@private
  BOOL hasKeyData_:1;
  BOOL hasKeyId_:1;
  NSData* keyData;
  int32_t keyId;
}
- (BOOL) hasKeyId;
- (BOOL) hasKeyData;
@property (readonly) int32_t keyId;
@property (readonly, retain) NSData* keyData;

+ (MBSKey*) defaultInstance;
- (MBSKey*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSKey_Builder*) builder;
+ (MBSKey_Builder*) builder;
+ (MBSKey_Builder*) builderWithPrototype:(MBSKey*) prototype;

+ (MBSKey*) parseFromData:(NSData*) data;
+ (MBSKey*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSKey*) parseFromInputStream:(NSInputStream*) input;
+ (MBSKey*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSKey*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSKey*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSKey*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSKey_Builder : PBGeneratedMessage_Builder {
@private
  MBSKey* result;
}

- (MBSKey*) defaultInstance;

- (MBSKey_Builder*) clear;
- (MBSKey_Builder*) clone;

- (MBSKey*) build;
- (MBSKey*) buildPartial;

- (MBSKey_Builder*) mergeFrom:(MBSKey*) other;
- (MBSKey_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSKey_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKeyId;
- (int32_t) keyId;
- (MBSKey_Builder*) setKeyId:(int32_t) value;
- (MBSKey_Builder*) clearKeyId;

- (BOOL) hasKeyData;
- (NSData*) keyData;
- (MBSKey_Builder*) setKeyData:(NSData*) value;
- (MBSKey_Builder*) clearKeyData;
@end

@interface MBSKeySet : PBGeneratedMessage {
@private
  NSMutableArray* mutableKeyList;
}
- (NSArray*) keyList;
- (MBSKey*) keyAtIndex:(int32_t) index;

+ (MBSKeySet*) defaultInstance;
- (MBSKeySet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSKeySet_Builder*) builder;
+ (MBSKeySet_Builder*) builder;
+ (MBSKeySet_Builder*) builderWithPrototype:(MBSKeySet*) prototype;

+ (MBSKeySet*) parseFromData:(NSData*) data;
+ (MBSKeySet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSKeySet*) parseFromInputStream:(NSInputStream*) input;
+ (MBSKeySet*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSKeySet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSKeySet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSKeySet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSKeySet_Builder : PBGeneratedMessage_Builder {
@private
  MBSKeySet* result;
}

- (MBSKeySet*) defaultInstance;

- (MBSKeySet_Builder*) clear;
- (MBSKeySet_Builder*) clone;

- (MBSKeySet*) build;
- (MBSKeySet*) buildPartial;

- (MBSKeySet_Builder*) mergeFrom:(MBSKeySet*) other;
- (MBSKeySet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSKeySet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) keyList;
- (MBSKey*) keyAtIndex:(int32_t) index;
- (MBSKeySet_Builder*) replaceKeyAtIndex:(int32_t) index with:(MBSKey*) value;
- (MBSKeySet_Builder*) addKey:(MBSKey*) value;
- (MBSKeySet_Builder*) addAllKey:(NSArray*) values;
- (MBSKeySet_Builder*) clearKeyList;
@end

@interface MBSFileExtendedAttribute : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasValue_:1;
  NSString* name;
  NSData* value;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSData* value;

+ (MBSFileExtendedAttribute*) defaultInstance;
- (MBSFileExtendedAttribute*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MBSFileExtendedAttribute_Builder*) builder;
+ (MBSFileExtendedAttribute_Builder*) builder;
+ (MBSFileExtendedAttribute_Builder*) builderWithPrototype:(MBSFileExtendedAttribute*) prototype;

+ (MBSFileExtendedAttribute*) parseFromData:(NSData*) data;
+ (MBSFileExtendedAttribute*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileExtendedAttribute*) parseFromInputStream:(NSInputStream*) input;
+ (MBSFileExtendedAttribute*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MBSFileExtendedAttribute*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MBSFileExtendedAttribute*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MBSFileExtendedAttribute*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MBSFileExtendedAttribute_Builder : PBGeneratedMessage_Builder {
@private
  MBSFileExtendedAttribute* result;
}

- (MBSFileExtendedAttribute*) defaultInstance;

- (MBSFileExtendedAttribute_Builder*) clear;
- (MBSFileExtendedAttribute_Builder*) clone;

- (MBSFileExtendedAttribute*) build;
- (MBSFileExtendedAttribute*) buildPartial;

- (MBSFileExtendedAttribute_Builder*) mergeFrom:(MBSFileExtendedAttribute*) other;
- (MBSFileExtendedAttribute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MBSFileExtendedAttribute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (MBSFileExtendedAttribute_Builder*) setName:(NSString*) value;
- (MBSFileExtendedAttribute_Builder*) clearName;

- (BOOL) hasValue;
- (NSData*) value;
- (MBSFileExtendedAttribute_Builder*) setValue:(NSData*) value;
- (MBSFileExtendedAttribute_Builder*) clearValue;
@end

